// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: ai-model/ai_model.proto

package aimodel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIModelService_CreateModel_FullMethodName    = "/ai.model.v1.AIModelService/CreateModel"
	AIModelService_GetModel_FullMethodName       = "/ai.model.v1.AIModelService/GetModel"
	AIModelService_ListModels_FullMethodName     = "/ai.model.v1.AIModelService/ListModels"
	AIModelService_UpdateModel_FullMethodName    = "/ai.model.v1.AIModelService/UpdateModel"
	AIModelService_DeleteModel_FullMethodName    = "/ai.model.v1.AIModelService/DeleteModel"
	AIModelService_GetCredentials_FullMethodName = "/ai.model.v1.AIModelService/GetCredentials"
	AIModelService_LogUsage_FullMethodName       = "/ai.model.v1.AIModelService/LogUsage"
	AIModelService_CheckQuota_FullMethodName     = "/ai.model.v1.AIModelService/CheckQuota"
	AIModelService_GetUsageStats_FullMethodName  = "/ai.model.v1.AIModelService/GetUsageStats"
)

// AIModelServiceClient is the client API for AIModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =======================
// AI Model Service
// =======================
type AIModelServiceClient interface {
	// Model Management (Admin APIs)
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*UpdateModelResponse, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*ResponseEmpty, error)
	// Internal APIs (gRPC only - no HTTP mapping)
	GetCredentials(ctx context.Context, in *GetCredentialsRequest, opts ...grpc.CallOption) (*GetCredentialsResponse, error)
	LogUsage(ctx context.Context, in *LogUsageRequest, opts ...grpc.CallOption) (*ResponseEmpty, error)
	CheckQuota(ctx context.Context, in *CheckQuotaRequest, opts ...grpc.CallOption) (*CheckQuotaResponse, error)
	// Analytics
	GetUsageStats(ctx context.Context, in *GetUsageStatsRequest, opts ...grpc.CallOption) (*GetUsageStatsResponse, error)
}

type aIModelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIModelServiceClient(cc grpc.ClientConnInterface) AIModelServiceClient {
	return &aIModelServiceClient{cc}
}

func (c *aIModelServiceClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateModelResponse)
	err := c.cc.Invoke(ctx, AIModelService_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelResponse)
	err := c.cc.Invoke(ctx, AIModelService_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, AIModelService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*UpdateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateModelResponse)
	err := c.cc.Invoke(ctx, AIModelService_UpdateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*ResponseEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseEmpty)
	err := c.cc.Invoke(ctx, AIModelService_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) GetCredentials(ctx context.Context, in *GetCredentialsRequest, opts ...grpc.CallOption) (*GetCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialsResponse)
	err := c.cc.Invoke(ctx, AIModelService_GetCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) LogUsage(ctx context.Context, in *LogUsageRequest, opts ...grpc.CallOption) (*ResponseEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseEmpty)
	err := c.cc.Invoke(ctx, AIModelService_LogUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) CheckQuota(ctx context.Context, in *CheckQuotaRequest, opts ...grpc.CallOption) (*CheckQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckQuotaResponse)
	err := c.cc.Invoke(ctx, AIModelService_CheckQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) GetUsageStats(ctx context.Context, in *GetUsageStatsRequest, opts ...grpc.CallOption) (*GetUsageStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsageStatsResponse)
	err := c.cc.Invoke(ctx, AIModelService_GetUsageStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIModelServiceServer is the server API for AIModelService service.
// All implementations must embed UnimplementedAIModelServiceServer
// for forward compatibility.
//
// =======================
// AI Model Service
// =======================
type AIModelServiceServer interface {
	// Model Management (Admin APIs)
	CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error)
	GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	UpdateModel(context.Context, *UpdateModelRequest) (*UpdateModelResponse, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*ResponseEmpty, error)
	// Internal APIs (gRPC only - no HTTP mapping)
	GetCredentials(context.Context, *GetCredentialsRequest) (*GetCredentialsResponse, error)
	LogUsage(context.Context, *LogUsageRequest) (*ResponseEmpty, error)
	CheckQuota(context.Context, *CheckQuotaRequest) (*CheckQuotaResponse, error)
	// Analytics
	GetUsageStats(context.Context, *GetUsageStatsRequest) (*GetUsageStatsResponse, error)
	mustEmbedUnimplementedAIModelServiceServer()
}

// UnimplementedAIModelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIModelServiceServer struct{}

func (UnimplementedAIModelServiceServer) CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedAIModelServiceServer) GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedAIModelServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAIModelServiceServer) UpdateModel(context.Context, *UpdateModelRequest) (*UpdateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateModel not implemented")
}
func (UnimplementedAIModelServiceServer) DeleteModel(context.Context, *DeleteModelRequest) (*ResponseEmpty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedAIModelServiceServer) GetCredentials(context.Context, *GetCredentialsRequest) (*GetCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentials not implemented")
}
func (UnimplementedAIModelServiceServer) LogUsage(context.Context, *LogUsageRequest) (*ResponseEmpty, error) {
	return nil, status.Error(codes.Unimplemented, "method LogUsage not implemented")
}
func (UnimplementedAIModelServiceServer) CheckQuota(context.Context, *CheckQuotaRequest) (*CheckQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckQuota not implemented")
}
func (UnimplementedAIModelServiceServer) GetUsageStats(context.Context, *GetUsageStatsRequest) (*GetUsageStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsageStats not implemented")
}
func (UnimplementedAIModelServiceServer) mustEmbedUnimplementedAIModelServiceServer() {}
func (UnimplementedAIModelServiceServer) testEmbeddedByValue()                        {}

// UnsafeAIModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIModelServiceServer will
// result in compilation errors.
type UnsafeAIModelServiceServer interface {
	mustEmbedUnimplementedAIModelServiceServer()
}

func RegisterAIModelServiceServer(s grpc.ServiceRegistrar, srv AIModelServiceServer) {
	// If the following call panics, it indicates UnimplementedAIModelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIModelService_ServiceDesc, srv)
}

func _AIModelService_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_UpdateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).UpdateModel(ctx, req.(*UpdateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_GetCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).GetCredentials(ctx, req.(*GetCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_LogUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).LogUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_LogUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).LogUsage(ctx, req.(*LogUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_CheckQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).CheckQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_CheckQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).CheckQuota(ctx, req.(*CheckQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_GetUsageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).GetUsageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_GetUsageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).GetUsageStats(ctx, req.(*GetUsageStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIModelService_ServiceDesc is the grpc.ServiceDesc for AIModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.model.v1.AIModelService",
	HandlerType: (*AIModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateModel",
			Handler:    _AIModelService_CreateModel_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _AIModelService_GetModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _AIModelService_ListModels_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _AIModelService_UpdateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _AIModelService_DeleteModel_Handler,
		},
		{
			MethodName: "GetCredentials",
			Handler:    _AIModelService_GetCredentials_Handler,
		},
		{
			MethodName: "LogUsage",
			Handler:    _AIModelService_LogUsage_Handler,
		},
		{
			MethodName: "CheckQuota",
			Handler:    _AIModelService_CheckQuota_Handler,
		},
		{
			MethodName: "GetUsageStats",
			Handler:    _AIModelService_GetUsageStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai-model/ai_model.proto",
}
