// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ba-agent/ba_agent.proto

package baagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequirementTier int32

const (
	RequirementTier_TIER_UNSPECIFIED RequirementTier = 0
	RequirementTier_TIER_PRD         RequirementTier = 1
	RequirementTier_TIER_URD_INDEX   RequirementTier = 2
	RequirementTier_TIER_URD_OUTLINE RequirementTier = 3
	RequirementTier_TIER_URD_FULL    RequirementTier = 4
)

// Enum value maps for RequirementTier.
var (
	RequirementTier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_PRD",
		2: "TIER_URD_INDEX",
		3: "TIER_URD_OUTLINE",
		4: "TIER_URD_FULL",
	}
	RequirementTier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"TIER_PRD":         1,
		"TIER_URD_INDEX":   2,
		"TIER_URD_OUTLINE": 3,
		"TIER_URD_FULL":    4,
	}
)

func (x RequirementTier) Enum() *RequirementTier {
	p := new(RequirementTier)
	*p = x
	return p
}

func (x RequirementTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequirementTier) Descriptor() protoreflect.EnumDescriptor {
	return file_ba_agent_ba_agent_proto_enumTypes[0].Descriptor()
}

func (RequirementTier) Type() protoreflect.EnumType {
	return &file_ba_agent_ba_agent_proto_enumTypes[0]
}

func (x RequirementTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequirementTier.Descriptor instead.
func (RequirementTier) EnumDescriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{0}
}

type GenerateRequirementRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Metadata         *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature        *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ProjectId        string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ParentDocumentId string                 `protobuf:"bytes,4,opt,name=parent_document_id,json=parentDocumentId,proto3" json:"parent_document_id,omitempty"` // PRD ID or Parent Tier ID
	Tier             RequirementTier        `protobuf:"varint,5,opt,name=tier,proto3,enum=baagent.v1.RequirementTier" json:"tier,omitempty"`
	ModuleName       string                 `protobuf:"bytes,6,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Content          string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"` // For initial PRD upload
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateRequirementRequest) Reset() {
	*x = GenerateRequirementRequest{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequirementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequirementRequest) ProtoMessage() {}

func (x *GenerateRequirementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequirementRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequirementRequest) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequirementRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GenerateRequirementRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GenerateRequirementRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GenerateRequirementRequest) GetParentDocumentId() string {
	if x != nil {
		return x.ParentDocumentId
	}
	return ""
}

func (x *GenerateRequirementRequest) GetTier() RequirementTier {
	if x != nil {
		return x.Tier
	}
	return RequirementTier_TIER_UNSPECIFIED
}

func (x *GenerateRequirementRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *GenerateRequirementRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetDocumentRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetDocumentRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ApproveRequirementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	TierId        string                 `protobuf:"bytes,3,opt,name=tier_id,json=tierId,proto3" json:"tier_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Tier          RequirementTier        `protobuf:"varint,5,opt,name=tier,proto3,enum=baagent.v1.RequirementTier" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequirementRequest) Reset() {
	*x = ApproveRequirementRequest{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequirementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequirementRequest) ProtoMessage() {}

func (x *ApproveRequirementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequirementRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequirementRequest) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveRequirementRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ApproveRequirementRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ApproveRequirementRequest) GetTierId() string {
	if x != nil {
		return x.TierId
	}
	return ""
}

func (x *ApproveRequirementRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ApproveRequirementRequest) GetTier() RequirementTier {
	if x != nil {
		return x.Tier
	}
	return RequirementTier_TIER_UNSPECIFIED
}

type ReviewRequirementRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Metadata         *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature        *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	DocumentId       string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Comment          string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	ActionType       string                 `protobuf:"bytes,5,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	AffectedSections string                 `protobuf:"bytes,6,opt,name=affected_sections,json=affectedSections,proto3" json:"affected_sections,omitempty"` // JSON string
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReviewRequirementRequest) Reset() {
	*x = ReviewRequirementRequest{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequirementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequirementRequest) ProtoMessage() {}

func (x *ReviewRequirementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequirementRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequirementRequest) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewRequirementRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReviewRequirementRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ReviewRequirementRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ReviewRequirementRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReviewRequirementRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ReviewRequirementRequest) GetAffectedSections() string {
	if x != nil {
		return x.AffectedSections
	}
	return ""
}

type ExecuteTaskPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TaskDescription string                 `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	MaxIterations   int32                  `protobuf:"varint,4,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	WorkflowMode    string                 `protobuf:"bytes,5,opt,name=workflow_mode,json=workflowMode,proto3" json:"workflow_mode,omitempty"` // "interactive" (default) or "pipeline" (future)
	History         []*ReActStep           `protobuf:"bytes,6,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteTaskPayload) Reset() {
	*x = ExecuteTaskPayload{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskPayload) ProtoMessage() {}

func (x *ExecuteTaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskPayload.ProtoReflect.Descriptor instead.
func (*ExecuteTaskPayload) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteTaskPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecuteTaskPayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteTaskPayload) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *ExecuteTaskPayload) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *ExecuteTaskPayload) GetWorkflowMode() string {
	if x != nil {
		return x.WorkflowMode
	}
	return ""
}

func (x *ExecuteTaskPayload) GetHistory() []*ReActStep {
	if x != nil {
		return x.History
	}
	return nil
}

type ExecuteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload       *ExecuteTaskPayload    `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteTaskRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteTaskRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ExecuteTaskRequest) GetPayload() *ExecuteTaskPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetTaskRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListToolsRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListToolsRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type GetMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryRequest) Reset() {
	*x = GetMemoryRequest{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryRequest) ProtoMessage() {}

func (x *GetMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryRequest) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetMemoryRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetMemoryRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GetMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ClearMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMemoryRequest) Reset() {
	*x = ClearMemoryRequest{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMemoryRequest) ProtoMessage() {}

func (x *ClearMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMemoryRequest.ProtoReflect.Descriptor instead.
func (*ClearMemoryRequest) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ClearMemoryRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClearMemoryRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ClearMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SubmitInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	InputData     string                 `protobuf:"bytes,4,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitInputRequest) Reset() {
	*x = SubmitInputRequest{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInputRequest) ProtoMessage() {}

func (x *SubmitInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInputRequest.ProtoReflect.Descriptor instead.
func (*SubmitInputRequest) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitInputRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SubmitInputRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SubmitInputRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitInputRequest) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{11}
}

func (x *EmptyResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EmptyResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EmptyResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type GenerateRequirementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,4,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequirementResponse) Reset() {
	*x = GenerateRequirementResponse{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequirementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequirementResponse) ProtoMessage() {}

func (x *GenerateRequirementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequirementResponse.ProtoReflect.Descriptor instead.
func (*GenerateRequirementResponse) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateRequirementResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GenerateRequirementResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GenerateRequirementResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GenerateRequirementResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ExecuteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Task          *AgentTask             `protobuf:"bytes,4,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskResponse) Reset() {
	*x = ExecuteTaskResponse{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse) ProtoMessage() {}

func (x *ExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTaskResponse) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteTaskResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteTaskResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ExecuteTaskResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteTaskResponse) GetTask() *AgentTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type StreamExecuteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Step          *ReActStep             `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	IsFinal       bool                   `protobuf:"varint,5,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExecuteTaskResponse) Reset() {
	*x = StreamExecuteTaskResponse{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExecuteTaskResponse) ProtoMessage() {}

func (x *StreamExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExecuteTaskResponse.ProtoReflect.Descriptor instead.
func (*StreamExecuteTaskResponse) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{14}
}

func (x *StreamExecuteTaskResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StreamExecuteTaskResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *StreamExecuteTaskResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StreamExecuteTaskResponse) GetStep() *ReActStep {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *StreamExecuteTaskResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Task          *AgentTask             `protobuf:"bytes,4,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{15}
}

func (x *GetTaskResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetTaskResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GetTaskResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetTaskResponse) GetTask() *AgentTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Tools         []*Tool                `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ListToolsResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListToolsResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ListToolsResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListToolsResponse) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

type GetMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Memory        *Memory                `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryResponse) Reset() {
	*x = GetMemoryResponse{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryResponse) ProtoMessage() {}

func (x *GetMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryResponse.ProtoReflect.Descriptor instead.
func (*GetMemoryResponse) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{17}
}

func (x *GetMemoryResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetMemoryResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GetMemoryResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetMemoryResponse) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

type ClearMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMemoryResponse) Reset() {
	*x = ClearMemoryResponse{}
	mi := &file_ba_agent_ba_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMemoryResponse) ProtoMessage() {}

func (x *ClearMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ba_agent_ba_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMemoryResponse.ProtoReflect.Descriptor instead.
func (*ClearMemoryResponse) Descriptor() ([]byte, []int) {
	return file_ba_agent_ba_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ClearMemoryResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClearMemoryResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ClearMemoryResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_ba_agent_ba_agent_proto protoreflect.FileDescriptor

const file_ba_agent_ba_agent_proto_rawDesc = "" +
	"\n" +
	"\x17ba-agent/ba_agent.proto\x12\n" +
	"baagent.v1\x1a\x13ba-agent/base.proto\"\xbc\x02\n" +
	"\x1aGenerateRequirementRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12,\n" +
	"\x12parent_document_id\x18\x04 \x01(\tR\x10parentDocumentId\x12/\n" +
	"\x04tier\x18\x05 \x01(\x0e2\x1b.baagent.v1.RequirementTierR\x04tier\x12\x1f\n" +
	"\vmodule_name\x18\x06 \x01(\tR\n" +
	"moduleName\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\"\x9c\x01\n" +
	"\x12GetDocumentRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\"\xe9\x01\n" +
	"\x19ApproveRequirementRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12\x17\n" +
	"\atier_id\x18\x03 \x01(\tR\x06tierId\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12/\n" +
	"\x04tier\x18\x05 \x01(\x0e2\x1b.baagent.v1.RequirementTierR\x04tier\"\x8a\x02\n" +
	"\x18ReviewRequirementRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1f\n" +
	"\vaction_type\x18\x05 \x01(\tR\n" +
	"actionType\x12+\n" +
	"\x11affected_sections\x18\x06 \x01(\tR\x10affectedSections\"\xf4\x01\n" +
	"\x12ExecuteTaskPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12)\n" +
	"\x10task_description\x18\x03 \x01(\tR\x0ftaskDescription\x12%\n" +
	"\x0emax_iterations\x18\x04 \x01(\x05R\rmaxIterations\x12#\n" +
	"\rworkflow_mode\x18\x05 \x01(\tR\fworkflowMode\x12/\n" +
	"\ahistory\x18\x06 \x03(\v2\x15.baagent.v1.ReActStepR\ahistory\"\xb5\x01\n" +
	"\x12ExecuteTaskRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x128\n" +
	"\apayload\x18\x03 \x01(\v2\x1e.baagent.v1.ExecuteTaskPayloadR\apayload\"\x90\x01\n" +
	"\x0eGetTaskRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\"y\n" +
	"\x10ListToolsRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\"\x98\x01\n" +
	"\x10GetMemoryRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x9a\x01\n" +
	"\x12ClearMemoryRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xb3\x01\n" +
	"\x12SubmitInputRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"input_data\x18\x04 \x01(\tR\tinputData\"\xa2\x01\n" +
	"\rEmptyResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12*\n" +
	"\x06result\x18\x03 \x01(\v2\x12.baagent.v1.ResultR\x06result\"\xb3\x01\n" +
	"\x1bGenerateRequirementResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x12*\n" +
	"\x06result\x18\x02 \x01(\v2\x12.baagent.v1.ResultR\x06result\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vdocument_id\x18\x04 \x01(\tR\n" +
	"documentId\"\xd3\x01\n" +
	"\x13ExecuteTaskResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12*\n" +
	"\x06result\x18\x03 \x01(\v2\x12.baagent.v1.ResultR\x06result\x12)\n" +
	"\x04task\x18\x04 \x01(\v2\x15.baagent.v1.AgentTaskR\x04task\"\xf4\x01\n" +
	"\x19StreamExecuteTaskResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12*\n" +
	"\x06result\x18\x03 \x01(\v2\x12.baagent.v1.ResultR\x06result\x12)\n" +
	"\x04step\x18\x04 \x01(\v2\x15.baagent.v1.ReActStepR\x04step\x12\x19\n" +
	"\bis_final\x18\x05 \x01(\bR\aisFinal\"\xcf\x01\n" +
	"\x0fGetTaskResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12*\n" +
	"\x06result\x18\x03 \x01(\v2\x12.baagent.v1.ResultR\x06result\x12)\n" +
	"\x04task\x18\x04 \x01(\v2\x15.baagent.v1.AgentTaskR\x04task\"\xce\x01\n" +
	"\x11ListToolsResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12*\n" +
	"\x06result\x18\x03 \x01(\v2\x12.baagent.v1.ResultR\x06result\x12&\n" +
	"\x05tools\x18\x04 \x03(\v2\x10.baagent.v1.ToolR\x05tools\"\xd2\x01\n" +
	"\x11GetMemoryResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12*\n" +
	"\x06result\x18\x03 \x01(\v2\x12.baagent.v1.ResultR\x06result\x12*\n" +
	"\x06memory\x18\x04 \x01(\v2\x12.baagent.v1.MemoryR\x06memory\"\xa8\x01\n" +
	"\x13ClearMemoryResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.baagent.v1.MetadataR\bmetadata\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.baagent.v1.SignatureR\tsignature\x12*\n" +
	"\x06result\x18\x03 \x01(\v2\x12.baagent.v1.ResultR\x06result*r\n" +
	"\x0fRequirementTier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bTIER_PRD\x10\x01\x12\x12\n" +
	"\x0eTIER_URD_INDEX\x10\x02\x12\x14\n" +
	"\x10TIER_URD_OUTLINE\x10\x03\x12\x11\n" +
	"\rTIER_URD_FULL\x10\x042\xeb\n" +
	"\n" +
	"\x0eBAAgentService\x12P\n" +
	"\vExecuteTask\x12\x1e.baagent.v1.ExecuteTaskRequest\x1a\x1f.baagent.v1.ExecuteTaskResponse\"\x00\x12X\n" +
	"\vSubmitInput\x12\x1e.baagent.v1.SubmitInputRequest\x1a%.baagent.v1.StreamExecuteTaskResponse\"\x000\x01\x12^\n" +
	"\x11StreamExecuteTask\x12\x1e.baagent.v1.ExecuteTaskRequest\x1a%.baagent.v1.StreamExecuteTaskResponse\"\x000\x01\x12D\n" +
	"\aGetTask\x12\x1a.baagent.v1.GetTaskRequest\x1a\x1b.baagent.v1.GetTaskResponse\"\x00\x12J\n" +
	"\tListTools\x12\x1c.baagent.v1.ListToolsRequest\x1a\x1d.baagent.v1.ListToolsResponse\"\x00\x12J\n" +
	"\tGetMemory\x12\x1c.baagent.v1.GetMemoryRequest\x1a\x1d.baagent.v1.GetMemoryResponse\"\x00\x12P\n" +
	"\vClearMemory\x12\x1e.baagent.v1.ClearMemoryRequest\x1a\x1f.baagent.v1.ClearMemoryResponse\"\x00\x12h\n" +
	"\x13GenerateRequirement\x12&.baagent.v1.GenerateRequirementRequest\x1a'.baagent.v1.GenerateRequirementResponse\"\x00\x12P\n" +
	"\vGetDocument\x12\x1e.baagent.v1.GetDocumentRequest\x1a\x1f.baagent.v1.ExecuteTaskResponse\"\x00\x12Q\n" +
	"\fGetTierIndex\x12\x1e.baagent.v1.GetDocumentRequest\x1a\x1f.baagent.v1.ExecuteTaskResponse\"\x00\x12S\n" +
	"\x0eGetTierOutline\x12\x1e.baagent.v1.GetDocumentRequest\x1a\x1f.baagent.v1.ExecuteTaskResponse\"\x00\x12P\n" +
	"\vGetTierFull\x12\x1e.baagent.v1.GetDocumentRequest\x1a\x1f.baagent.v1.ExecuteTaskResponse\"\x00\x12X\n" +
	"\x12ApproveRequirement\x12%.baagent.v1.ApproveRequirementRequest\x1a\x19.baagent.v1.EmptyResponse\"\x00\x12V\n" +
	"\x11ReviewRequirement\x12$.baagent.v1.ReviewRequirementRequest\x1a\x19.baagent.v1.EmptyResponse\"\x00\x12j\n" +
	"\x15RegenerateRequirement\x12&.baagent.v1.GenerateRequirementRequest\x1a'.baagent.v1.GenerateRequirementResponse\"\x00\x12I\n" +
	"\n" +
	"GetLineage\x12\x1e.baagent.v1.GetDocumentRequest\x1a\x19.baagent.v1.EmptyResponse\"\x00BT\n" +
	"\x1fcom.blcvn.kratos.protos.baagentZ1github.com/blcvn/kratos-proto/go/ba-agent;baagentb\x06proto3"

var (
	file_ba_agent_ba_agent_proto_rawDescOnce sync.Once
	file_ba_agent_ba_agent_proto_rawDescData []byte
)

func file_ba_agent_ba_agent_proto_rawDescGZIP() []byte {
	file_ba_agent_ba_agent_proto_rawDescOnce.Do(func() {
		file_ba_agent_ba_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ba_agent_ba_agent_proto_rawDesc), len(file_ba_agent_ba_agent_proto_rawDesc)))
	})
	return file_ba_agent_ba_agent_proto_rawDescData
}

var file_ba_agent_ba_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ba_agent_ba_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_ba_agent_ba_agent_proto_goTypes = []any{
	(RequirementTier)(0),                // 0: baagent.v1.RequirementTier
	(*GenerateRequirementRequest)(nil),  // 1: baagent.v1.GenerateRequirementRequest
	(*GetDocumentRequest)(nil),          // 2: baagent.v1.GetDocumentRequest
	(*ApproveRequirementRequest)(nil),   // 3: baagent.v1.ApproveRequirementRequest
	(*ReviewRequirementRequest)(nil),    // 4: baagent.v1.ReviewRequirementRequest
	(*ExecuteTaskPayload)(nil),          // 5: baagent.v1.ExecuteTaskPayload
	(*ExecuteTaskRequest)(nil),          // 6: baagent.v1.ExecuteTaskRequest
	(*GetTaskRequest)(nil),              // 7: baagent.v1.GetTaskRequest
	(*ListToolsRequest)(nil),            // 8: baagent.v1.ListToolsRequest
	(*GetMemoryRequest)(nil),            // 9: baagent.v1.GetMemoryRequest
	(*ClearMemoryRequest)(nil),          // 10: baagent.v1.ClearMemoryRequest
	(*SubmitInputRequest)(nil),          // 11: baagent.v1.SubmitInputRequest
	(*EmptyResponse)(nil),               // 12: baagent.v1.EmptyResponse
	(*GenerateRequirementResponse)(nil), // 13: baagent.v1.GenerateRequirementResponse
	(*ExecuteTaskResponse)(nil),         // 14: baagent.v1.ExecuteTaskResponse
	(*StreamExecuteTaskResponse)(nil),   // 15: baagent.v1.StreamExecuteTaskResponse
	(*GetTaskResponse)(nil),             // 16: baagent.v1.GetTaskResponse
	(*ListToolsResponse)(nil),           // 17: baagent.v1.ListToolsResponse
	(*GetMemoryResponse)(nil),           // 18: baagent.v1.GetMemoryResponse
	(*ClearMemoryResponse)(nil),         // 19: baagent.v1.ClearMemoryResponse
	(*Metadata)(nil),                    // 20: baagent.v1.Metadata
	(*Signature)(nil),                   // 21: baagent.v1.Signature
	(*ReActStep)(nil),                   // 22: baagent.v1.ReActStep
	(*Result)(nil),                      // 23: baagent.v1.Result
	(*AgentTask)(nil),                   // 24: baagent.v1.AgentTask
	(*Tool)(nil),                        // 25: baagent.v1.Tool
	(*Memory)(nil),                      // 26: baagent.v1.Memory
}
var file_ba_agent_ba_agent_proto_depIdxs = []int32{
	20, // 0: baagent.v1.GenerateRequirementRequest.metadata:type_name -> baagent.v1.Metadata
	21, // 1: baagent.v1.GenerateRequirementRequest.signature:type_name -> baagent.v1.Signature
	0,  // 2: baagent.v1.GenerateRequirementRequest.tier:type_name -> baagent.v1.RequirementTier
	20, // 3: baagent.v1.GetDocumentRequest.metadata:type_name -> baagent.v1.Metadata
	21, // 4: baagent.v1.GetDocumentRequest.signature:type_name -> baagent.v1.Signature
	20, // 5: baagent.v1.ApproveRequirementRequest.metadata:type_name -> baagent.v1.Metadata
	21, // 6: baagent.v1.ApproveRequirementRequest.signature:type_name -> baagent.v1.Signature
	0,  // 7: baagent.v1.ApproveRequirementRequest.tier:type_name -> baagent.v1.RequirementTier
	20, // 8: baagent.v1.ReviewRequirementRequest.metadata:type_name -> baagent.v1.Metadata
	21, // 9: baagent.v1.ReviewRequirementRequest.signature:type_name -> baagent.v1.Signature
	22, // 10: baagent.v1.ExecuteTaskPayload.history:type_name -> baagent.v1.ReActStep
	20, // 11: baagent.v1.ExecuteTaskRequest.metadata:type_name -> baagent.v1.Metadata
	21, // 12: baagent.v1.ExecuteTaskRequest.signature:type_name -> baagent.v1.Signature
	5,  // 13: baagent.v1.ExecuteTaskRequest.payload:type_name -> baagent.v1.ExecuteTaskPayload
	20, // 14: baagent.v1.GetTaskRequest.metadata:type_name -> baagent.v1.Metadata
	21, // 15: baagent.v1.GetTaskRequest.signature:type_name -> baagent.v1.Signature
	20, // 16: baagent.v1.ListToolsRequest.metadata:type_name -> baagent.v1.Metadata
	21, // 17: baagent.v1.ListToolsRequest.signature:type_name -> baagent.v1.Signature
	20, // 18: baagent.v1.GetMemoryRequest.metadata:type_name -> baagent.v1.Metadata
	21, // 19: baagent.v1.GetMemoryRequest.signature:type_name -> baagent.v1.Signature
	20, // 20: baagent.v1.ClearMemoryRequest.metadata:type_name -> baagent.v1.Metadata
	21, // 21: baagent.v1.ClearMemoryRequest.signature:type_name -> baagent.v1.Signature
	20, // 22: baagent.v1.SubmitInputRequest.metadata:type_name -> baagent.v1.Metadata
	21, // 23: baagent.v1.SubmitInputRequest.signature:type_name -> baagent.v1.Signature
	20, // 24: baagent.v1.EmptyResponse.metadata:type_name -> baagent.v1.Metadata
	21, // 25: baagent.v1.EmptyResponse.signature:type_name -> baagent.v1.Signature
	23, // 26: baagent.v1.EmptyResponse.result:type_name -> baagent.v1.Result
	20, // 27: baagent.v1.GenerateRequirementResponse.metadata:type_name -> baagent.v1.Metadata
	23, // 28: baagent.v1.GenerateRequirementResponse.result:type_name -> baagent.v1.Result
	20, // 29: baagent.v1.ExecuteTaskResponse.metadata:type_name -> baagent.v1.Metadata
	21, // 30: baagent.v1.ExecuteTaskResponse.signature:type_name -> baagent.v1.Signature
	23, // 31: baagent.v1.ExecuteTaskResponse.result:type_name -> baagent.v1.Result
	24, // 32: baagent.v1.ExecuteTaskResponse.task:type_name -> baagent.v1.AgentTask
	20, // 33: baagent.v1.StreamExecuteTaskResponse.metadata:type_name -> baagent.v1.Metadata
	21, // 34: baagent.v1.StreamExecuteTaskResponse.signature:type_name -> baagent.v1.Signature
	23, // 35: baagent.v1.StreamExecuteTaskResponse.result:type_name -> baagent.v1.Result
	22, // 36: baagent.v1.StreamExecuteTaskResponse.step:type_name -> baagent.v1.ReActStep
	20, // 37: baagent.v1.GetTaskResponse.metadata:type_name -> baagent.v1.Metadata
	21, // 38: baagent.v1.GetTaskResponse.signature:type_name -> baagent.v1.Signature
	23, // 39: baagent.v1.GetTaskResponse.result:type_name -> baagent.v1.Result
	24, // 40: baagent.v1.GetTaskResponse.task:type_name -> baagent.v1.AgentTask
	20, // 41: baagent.v1.ListToolsResponse.metadata:type_name -> baagent.v1.Metadata
	21, // 42: baagent.v1.ListToolsResponse.signature:type_name -> baagent.v1.Signature
	23, // 43: baagent.v1.ListToolsResponse.result:type_name -> baagent.v1.Result
	25, // 44: baagent.v1.ListToolsResponse.tools:type_name -> baagent.v1.Tool
	20, // 45: baagent.v1.GetMemoryResponse.metadata:type_name -> baagent.v1.Metadata
	21, // 46: baagent.v1.GetMemoryResponse.signature:type_name -> baagent.v1.Signature
	23, // 47: baagent.v1.GetMemoryResponse.result:type_name -> baagent.v1.Result
	26, // 48: baagent.v1.GetMemoryResponse.memory:type_name -> baagent.v1.Memory
	20, // 49: baagent.v1.ClearMemoryResponse.metadata:type_name -> baagent.v1.Metadata
	21, // 50: baagent.v1.ClearMemoryResponse.signature:type_name -> baagent.v1.Signature
	23, // 51: baagent.v1.ClearMemoryResponse.result:type_name -> baagent.v1.Result
	6,  // 52: baagent.v1.BAAgentService.ExecuteTask:input_type -> baagent.v1.ExecuteTaskRequest
	11, // 53: baagent.v1.BAAgentService.SubmitInput:input_type -> baagent.v1.SubmitInputRequest
	6,  // 54: baagent.v1.BAAgentService.StreamExecuteTask:input_type -> baagent.v1.ExecuteTaskRequest
	7,  // 55: baagent.v1.BAAgentService.GetTask:input_type -> baagent.v1.GetTaskRequest
	8,  // 56: baagent.v1.BAAgentService.ListTools:input_type -> baagent.v1.ListToolsRequest
	9,  // 57: baagent.v1.BAAgentService.GetMemory:input_type -> baagent.v1.GetMemoryRequest
	10, // 58: baagent.v1.BAAgentService.ClearMemory:input_type -> baagent.v1.ClearMemoryRequest
	1,  // 59: baagent.v1.BAAgentService.GenerateRequirement:input_type -> baagent.v1.GenerateRequirementRequest
	2,  // 60: baagent.v1.BAAgentService.GetDocument:input_type -> baagent.v1.GetDocumentRequest
	2,  // 61: baagent.v1.BAAgentService.GetTierIndex:input_type -> baagent.v1.GetDocumentRequest
	2,  // 62: baagent.v1.BAAgentService.GetTierOutline:input_type -> baagent.v1.GetDocumentRequest
	2,  // 63: baagent.v1.BAAgentService.GetTierFull:input_type -> baagent.v1.GetDocumentRequest
	3,  // 64: baagent.v1.BAAgentService.ApproveRequirement:input_type -> baagent.v1.ApproveRequirementRequest
	4,  // 65: baagent.v1.BAAgentService.ReviewRequirement:input_type -> baagent.v1.ReviewRequirementRequest
	1,  // 66: baagent.v1.BAAgentService.RegenerateRequirement:input_type -> baagent.v1.GenerateRequirementRequest
	2,  // 67: baagent.v1.BAAgentService.GetLineage:input_type -> baagent.v1.GetDocumentRequest
	14, // 68: baagent.v1.BAAgentService.ExecuteTask:output_type -> baagent.v1.ExecuteTaskResponse
	15, // 69: baagent.v1.BAAgentService.SubmitInput:output_type -> baagent.v1.StreamExecuteTaskResponse
	15, // 70: baagent.v1.BAAgentService.StreamExecuteTask:output_type -> baagent.v1.StreamExecuteTaskResponse
	16, // 71: baagent.v1.BAAgentService.GetTask:output_type -> baagent.v1.GetTaskResponse
	17, // 72: baagent.v1.BAAgentService.ListTools:output_type -> baagent.v1.ListToolsResponse
	18, // 73: baagent.v1.BAAgentService.GetMemory:output_type -> baagent.v1.GetMemoryResponse
	19, // 74: baagent.v1.BAAgentService.ClearMemory:output_type -> baagent.v1.ClearMemoryResponse
	13, // 75: baagent.v1.BAAgentService.GenerateRequirement:output_type -> baagent.v1.GenerateRequirementResponse
	14, // 76: baagent.v1.BAAgentService.GetDocument:output_type -> baagent.v1.ExecuteTaskResponse
	14, // 77: baagent.v1.BAAgentService.GetTierIndex:output_type -> baagent.v1.ExecuteTaskResponse
	14, // 78: baagent.v1.BAAgentService.GetTierOutline:output_type -> baagent.v1.ExecuteTaskResponse
	14, // 79: baagent.v1.BAAgentService.GetTierFull:output_type -> baagent.v1.ExecuteTaskResponse
	12, // 80: baagent.v1.BAAgentService.ApproveRequirement:output_type -> baagent.v1.EmptyResponse
	12, // 81: baagent.v1.BAAgentService.ReviewRequirement:output_type -> baagent.v1.EmptyResponse
	13, // 82: baagent.v1.BAAgentService.RegenerateRequirement:output_type -> baagent.v1.GenerateRequirementResponse
	12, // 83: baagent.v1.BAAgentService.GetLineage:output_type -> baagent.v1.EmptyResponse
	68, // [68:84] is the sub-list for method output_type
	52, // [52:68] is the sub-list for method input_type
	52, // [52:52] is the sub-list for extension type_name
	52, // [52:52] is the sub-list for extension extendee
	0,  // [0:52] is the sub-list for field type_name
}

func init() { file_ba_agent_ba_agent_proto_init() }
func file_ba_agent_ba_agent_proto_init() {
	if File_ba_agent_ba_agent_proto != nil {
		return
	}
	file_ba_agent_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ba_agent_ba_agent_proto_rawDesc), len(file_ba_agent_ba_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ba_agent_ba_agent_proto_goTypes,
		DependencyIndexes: file_ba_agent_ba_agent_proto_depIdxs,
		EnumInfos:         file_ba_agent_ba_agent_proto_enumTypes,
		MessageInfos:      file_ba_agent_ba_agent_proto_msgTypes,
	}.Build()
	File_ba_agent_ba_agent_proto = out.File
	file_ba_agent_ba_agent_proto_goTypes = nil
	file_ba_agent_ba_agent_proto_depIdxs = nil
}
