// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: workspace/workspace.proto

package workspace

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspaceService_CreateProject_FullMethodName                    = "/workspace.v1.WorkspaceService/CreateProject"
	WorkspaceService_ListProjects_FullMethodName                     = "/workspace.v1.WorkspaceService/ListProjects"
	WorkspaceService_GetProject_FullMethodName                       = "/workspace.v1.WorkspaceService/GetProject"
	WorkspaceService_UpdateProject_FullMethodName                    = "/workspace.v1.WorkspaceService/UpdateProject"
	WorkspaceService_DeleteProject_FullMethodName                    = "/workspace.v1.WorkspaceService/DeleteProject"
	WorkspaceService_AddProjectMember_FullMethodName                 = "/workspace.v1.WorkspaceService/AddProjectMember"
	WorkspaceService_RemoveProjectMember_FullMethodName              = "/workspace.v1.WorkspaceService/RemoveProjectMember"
	WorkspaceService_GetFeatureTree_FullMethodName                   = "/workspace.v1.WorkspaceService/GetFeatureTree"
	WorkspaceService_CreateFeature_FullMethodName                    = "/workspace.v1.WorkspaceService/CreateFeature"
	WorkspaceService_CreateFeatureGroup_FullMethodName               = "/workspace.v1.WorkspaceService/CreateFeatureGroup"
	WorkspaceService_GetFeature_FullMethodName                       = "/workspace.v1.WorkspaceService/GetFeature"
	WorkspaceService_UpdateFeature_FullMethodName                    = "/workspace.v1.WorkspaceService/UpdateFeature"
	WorkspaceService_DeleteFeature_FullMethodName                    = "/workspace.v1.WorkspaceService/DeleteFeature"
	WorkspaceService_CreateDocument_FullMethodName                   = "/workspace.v1.WorkspaceService/CreateDocument"
	WorkspaceService_ListDocuments_FullMethodName                    = "/workspace.v1.WorkspaceService/ListDocuments"
	WorkspaceService_ListDocumentSections_FullMethodName             = "/workspace.v1.WorkspaceService/ListDocumentSections"
	WorkspaceService_GetDocumentSection_FullMethodName               = "/workspace.v1.WorkspaceService/GetDocumentSection"
	WorkspaceService_CreateDocumentSection_FullMethodName            = "/workspace.v1.WorkspaceService/CreateDocumentSection"
	WorkspaceService_UpdateDocumentSection_FullMethodName            = "/workspace.v1.WorkspaceService/UpdateDocumentSection"
	WorkspaceService_UpdateDocumentSectionContent_FullMethodName     = "/workspace.v1.WorkspaceService/UpdateDocumentSectionContent"
	WorkspaceService_CreateDocumentSectionVersion_FullMethodName     = "/workspace.v1.WorkspaceService/CreateDocumentSectionVersion"
	WorkspaceService_ListDocumentSectionVersions_FullMethodName      = "/workspace.v1.WorkspaceService/ListDocumentSectionVersions"
	WorkspaceService_GetCurrentDocumentSectionVersion_FullMethodName = "/workspace.v1.WorkspaceService/GetCurrentDocumentSectionVersion"
	WorkspaceService_SetCurrentDocumentSectionVersion_FullMethodName = "/workspace.v1.WorkspaceService/SetCurrentDocumentSectionVersion"
	WorkspaceService_ListChatMessages_FullMethodName                 = "/workspace.v1.WorkspaceService/ListChatMessages"
	WorkspaceService_AppendChatMessage_FullMethodName                = "/workspace.v1.WorkspaceService/AppendChatMessage"
	WorkspaceService_CreateSession_FullMethodName                    = "/workspace.v1.WorkspaceService/CreateSession"
	WorkspaceService_UpdateSessionContext_FullMethodName             = "/workspace.v1.WorkspaceService/UpdateSessionContext"
	WorkspaceService_GetSession_FullMethodName                       = "/workspace.v1.WorkspaceService/GetSession"
	WorkspaceService_ListProjectSessions_FullMethodName              = "/workspace.v1.WorkspaceService/ListProjectSessions"
)

// WorkspaceServiceClient is the client API for WorkspaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =======================
// Workspace Service Definition
// =======================
type WorkspaceServiceClient interface {
	// 1. Projects
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsReply, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	// 1.6 & 1.7 Project Members
	AddProjectMember(ctx context.Context, in *AddProjectMemberRequest, opts ...grpc.CallOption) (*ProjectMemberReply, error)
	RemoveProjectMember(ctx context.Context, in *RemoveProjectMemberRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	// 2. Features
	GetFeatureTree(ctx context.Context, in *GetFeatureTreeRequest, opts ...grpc.CallOption) (*GetFeatureTreeReply, error)
	CreateFeature(ctx context.Context, in *CreateFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error)
	CreateFeatureGroup(ctx context.Context, in *CreateFeatureGroupRequest, opts ...grpc.CallOption) (*FeatureReply, error)
	GetFeature(ctx context.Context, in *GetFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error)
	UpdateFeature(ctx context.Context, in *UpdateFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error)
	DeleteFeature(ctx context.Context, in *DeleteFeatureRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	// 3. Documents
	CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*DocumentReply, error)
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsReply, error)
	ListDocumentSections(ctx context.Context, in *ListDocumentSectionsRequest, opts ...grpc.CallOption) (*ListDocumentSectionsReply, error)
	GetDocumentSection(ctx context.Context, in *GetDocumentSectionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error)
	CreateDocumentSection(ctx context.Context, in *CreateDocumentSectionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error)
	UpdateDocumentSection(ctx context.Context, in *UpdateDocumentSectionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error)
	UpdateDocumentSectionContent(ctx context.Context, in *UpdateDocumentSectionContentRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error)
	// Section Versioning APIs
	CreateDocumentSectionVersion(ctx context.Context, in *CreateDocumentSectionVersionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error)
	ListDocumentSectionVersions(ctx context.Context, in *ListDocumentSectionVersionsRequest, opts ...grpc.CallOption) (*ListDocumentSectionsReply, error)
	GetCurrentDocumentSectionVersion(ctx context.Context, in *GetCurrentDocumentSectionVersionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error)
	SetCurrentDocumentSectionVersion(ctx context.Context, in *SetCurrentDocumentSectionVersionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error)
	// 4. Chat History
	ListChatMessages(ctx context.Context, in *ListChatMessagesRequest, opts ...grpc.CallOption) (*ListChatMessagesReply, error)
	AppendChatMessage(ctx context.Context, in *AppendChatMessageRequest, opts ...grpc.CallOption) (*ChatMessageReply, error)
	// 5. Sessions
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionReply, error)
	UpdateSessionContext(ctx context.Context, in *UpdateSessionContextRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionReply, error)
	ListProjectSessions(ctx context.Context, in *ListProjectSessionsRequest, opts ...grpc.CallOption) (*ListSessionsReply, error)
}

type workspaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceServiceClient(cc grpc.ClientConnInterface) WorkspaceServiceClient {
	return &workspaceServiceClient{cc}
}

func (c *workspaceServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectReply)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsReply)
	err := c.cc.Invoke(ctx, WorkspaceService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectReply)
	err := c.cc.Invoke(ctx, WorkspaceService_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectReply)
	err := c.cc.Invoke(ctx, WorkspaceService_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, WorkspaceService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) AddProjectMember(ctx context.Context, in *AddProjectMemberRequest, opts ...grpc.CallOption) (*ProjectMemberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectMemberReply)
	err := c.cc.Invoke(ctx, WorkspaceService_AddProjectMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) RemoveProjectMember(ctx context.Context, in *RemoveProjectMemberRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, WorkspaceService_RemoveProjectMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetFeatureTree(ctx context.Context, in *GetFeatureTreeRequest, opts ...grpc.CallOption) (*GetFeatureTreeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeatureTreeReply)
	err := c.cc.Invoke(ctx, WorkspaceService_GetFeatureTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) CreateFeature(ctx context.Context, in *CreateFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureReply)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) CreateFeatureGroup(ctx context.Context, in *CreateFeatureGroupRequest, opts ...grpc.CallOption) (*FeatureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureReply)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateFeatureGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetFeature(ctx context.Context, in *GetFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureReply)
	err := c.cc.Invoke(ctx, WorkspaceService_GetFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) UpdateFeature(ctx context.Context, in *UpdateFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureReply)
	err := c.cc.Invoke(ctx, WorkspaceService_UpdateFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) DeleteFeature(ctx context.Context, in *DeleteFeatureRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, WorkspaceService_DeleteFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*DocumentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentReply)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsReply)
	err := c.cc.Invoke(ctx, WorkspaceService_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListDocumentSections(ctx context.Context, in *ListDocumentSectionsRequest, opts ...grpc.CallOption) (*ListDocumentSectionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentSectionsReply)
	err := c.cc.Invoke(ctx, WorkspaceService_ListDocumentSections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetDocumentSection(ctx context.Context, in *GetDocumentSectionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentSectionReply)
	err := c.cc.Invoke(ctx, WorkspaceService_GetDocumentSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) CreateDocumentSection(ctx context.Context, in *CreateDocumentSectionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentSectionReply)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateDocumentSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) UpdateDocumentSection(ctx context.Context, in *UpdateDocumentSectionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentSectionReply)
	err := c.cc.Invoke(ctx, WorkspaceService_UpdateDocumentSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) UpdateDocumentSectionContent(ctx context.Context, in *UpdateDocumentSectionContentRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentSectionReply)
	err := c.cc.Invoke(ctx, WorkspaceService_UpdateDocumentSectionContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) CreateDocumentSectionVersion(ctx context.Context, in *CreateDocumentSectionVersionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentSectionReply)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateDocumentSectionVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListDocumentSectionVersions(ctx context.Context, in *ListDocumentSectionVersionsRequest, opts ...grpc.CallOption) (*ListDocumentSectionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentSectionsReply)
	err := c.cc.Invoke(ctx, WorkspaceService_ListDocumentSectionVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetCurrentDocumentSectionVersion(ctx context.Context, in *GetCurrentDocumentSectionVersionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentSectionReply)
	err := c.cc.Invoke(ctx, WorkspaceService_GetCurrentDocumentSectionVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) SetCurrentDocumentSectionVersion(ctx context.Context, in *SetCurrentDocumentSectionVersionRequest, opts ...grpc.CallOption) (*DocumentSectionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentSectionReply)
	err := c.cc.Invoke(ctx, WorkspaceService_SetCurrentDocumentSectionVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListChatMessages(ctx context.Context, in *ListChatMessagesRequest, opts ...grpc.CallOption) (*ListChatMessagesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatMessagesReply)
	err := c.cc.Invoke(ctx, WorkspaceService_ListChatMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) AppendChatMessage(ctx context.Context, in *AppendChatMessageRequest, opts ...grpc.CallOption) (*ChatMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMessageReply)
	err := c.cc.Invoke(ctx, WorkspaceService_AppendChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionReply)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) UpdateSessionContext(ctx context.Context, in *UpdateSessionContextRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, WorkspaceService_UpdateSessionContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionReply)
	err := c.cc.Invoke(ctx, WorkspaceService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListProjectSessions(ctx context.Context, in *ListProjectSessionsRequest, opts ...grpc.CallOption) (*ListSessionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsReply)
	err := c.cc.Invoke(ctx, WorkspaceService_ListProjectSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceServiceServer is the server API for WorkspaceService service.
// All implementations must embed UnimplementedWorkspaceServiceServer
// for forward compatibility.
//
// =======================
// Workspace Service Definition
// =======================
type WorkspaceServiceServer interface {
	// 1. Projects
	CreateProject(context.Context, *CreateProjectRequest) (*ProjectReply, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsReply, error)
	GetProject(context.Context, *GetProjectRequest) (*ProjectReply, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectReply, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*EmptyReply, error)
	// 1.6 & 1.7 Project Members
	AddProjectMember(context.Context, *AddProjectMemberRequest) (*ProjectMemberReply, error)
	RemoveProjectMember(context.Context, *RemoveProjectMemberRequest) (*EmptyReply, error)
	// 2. Features
	GetFeatureTree(context.Context, *GetFeatureTreeRequest) (*GetFeatureTreeReply, error)
	CreateFeature(context.Context, *CreateFeatureRequest) (*FeatureReply, error)
	CreateFeatureGroup(context.Context, *CreateFeatureGroupRequest) (*FeatureReply, error)
	GetFeature(context.Context, *GetFeatureRequest) (*FeatureReply, error)
	UpdateFeature(context.Context, *UpdateFeatureRequest) (*FeatureReply, error)
	DeleteFeature(context.Context, *DeleteFeatureRequest) (*EmptyReply, error)
	// 3. Documents
	CreateDocument(context.Context, *CreateDocumentRequest) (*DocumentReply, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsReply, error)
	ListDocumentSections(context.Context, *ListDocumentSectionsRequest) (*ListDocumentSectionsReply, error)
	GetDocumentSection(context.Context, *GetDocumentSectionRequest) (*DocumentSectionReply, error)
	CreateDocumentSection(context.Context, *CreateDocumentSectionRequest) (*DocumentSectionReply, error)
	UpdateDocumentSection(context.Context, *UpdateDocumentSectionRequest) (*DocumentSectionReply, error)
	UpdateDocumentSectionContent(context.Context, *UpdateDocumentSectionContentRequest) (*DocumentSectionReply, error)
	// Section Versioning APIs
	CreateDocumentSectionVersion(context.Context, *CreateDocumentSectionVersionRequest) (*DocumentSectionReply, error)
	ListDocumentSectionVersions(context.Context, *ListDocumentSectionVersionsRequest) (*ListDocumentSectionsReply, error)
	GetCurrentDocumentSectionVersion(context.Context, *GetCurrentDocumentSectionVersionRequest) (*DocumentSectionReply, error)
	SetCurrentDocumentSectionVersion(context.Context, *SetCurrentDocumentSectionVersionRequest) (*DocumentSectionReply, error)
	// 4. Chat History
	ListChatMessages(context.Context, *ListChatMessagesRequest) (*ListChatMessagesReply, error)
	AppendChatMessage(context.Context, *AppendChatMessageRequest) (*ChatMessageReply, error)
	// 5. Sessions
	CreateSession(context.Context, *CreateSessionRequest) (*SessionReply, error)
	UpdateSessionContext(context.Context, *UpdateSessionContextRequest) (*EmptyReply, error)
	GetSession(context.Context, *GetSessionRequest) (*SessionReply, error)
	ListProjectSessions(context.Context, *ListProjectSessionsRequest) (*ListSessionsReply, error)
	mustEmbedUnimplementedWorkspaceServiceServer()
}

// UnimplementedWorkspaceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceServiceServer struct{}

func (UnimplementedWorkspaceServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*ProjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetProject(context.Context, *GetProjectRequest) (*ProjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedWorkspaceServiceServer) UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedWorkspaceServiceServer) DeleteProject(context.Context, *DeleteProjectRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedWorkspaceServiceServer) AddProjectMember(context.Context, *AddProjectMemberRequest) (*ProjectMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProjectMember not implemented")
}
func (UnimplementedWorkspaceServiceServer) RemoveProjectMember(context.Context, *RemoveProjectMemberRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProjectMember not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetFeatureTree(context.Context, *GetFeatureTreeRequest) (*GetFeatureTreeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeatureTree not implemented")
}
func (UnimplementedWorkspaceServiceServer) CreateFeature(context.Context, *CreateFeatureRequest) (*FeatureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFeature not implemented")
}
func (UnimplementedWorkspaceServiceServer) CreateFeatureGroup(context.Context, *CreateFeatureGroupRequest) (*FeatureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFeatureGroup not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetFeature(context.Context, *GetFeatureRequest) (*FeatureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeature not implemented")
}
func (UnimplementedWorkspaceServiceServer) UpdateFeature(context.Context, *UpdateFeatureRequest) (*FeatureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFeature not implemented")
}
func (UnimplementedWorkspaceServiceServer) DeleteFeature(context.Context, *DeleteFeatureRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFeature not implemented")
}
func (UnimplementedWorkspaceServiceServer) CreateDocument(context.Context, *CreateDocumentRequest) (*DocumentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDocument not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListDocumentSections(context.Context, *ListDocumentSectionsRequest) (*ListDocumentSectionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocumentSections not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetDocumentSection(context.Context, *GetDocumentSectionRequest) (*DocumentSectionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentSection not implemented")
}
func (UnimplementedWorkspaceServiceServer) CreateDocumentSection(context.Context, *CreateDocumentSectionRequest) (*DocumentSectionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDocumentSection not implemented")
}
func (UnimplementedWorkspaceServiceServer) UpdateDocumentSection(context.Context, *UpdateDocumentSectionRequest) (*DocumentSectionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocumentSection not implemented")
}
func (UnimplementedWorkspaceServiceServer) UpdateDocumentSectionContent(context.Context, *UpdateDocumentSectionContentRequest) (*DocumentSectionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocumentSectionContent not implemented")
}
func (UnimplementedWorkspaceServiceServer) CreateDocumentSectionVersion(context.Context, *CreateDocumentSectionVersionRequest) (*DocumentSectionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDocumentSectionVersion not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListDocumentSectionVersions(context.Context, *ListDocumentSectionVersionsRequest) (*ListDocumentSectionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocumentSectionVersions not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetCurrentDocumentSectionVersion(context.Context, *GetCurrentDocumentSectionVersionRequest) (*DocumentSectionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentDocumentSectionVersion not implemented")
}
func (UnimplementedWorkspaceServiceServer) SetCurrentDocumentSectionVersion(context.Context, *SetCurrentDocumentSectionVersionRequest) (*DocumentSectionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCurrentDocumentSectionVersion not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListChatMessages(context.Context, *ListChatMessagesRequest) (*ListChatMessagesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChatMessages not implemented")
}
func (UnimplementedWorkspaceServiceServer) AppendChatMessage(context.Context, *AppendChatMessageRequest) (*ChatMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendChatMessage not implemented")
}
func (UnimplementedWorkspaceServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*SessionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedWorkspaceServiceServer) UpdateSessionContext(context.Context, *UpdateSessionContextRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSessionContext not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetSession(context.Context, *GetSessionRequest) (*SessionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListProjectSessions(context.Context, *ListProjectSessionsRequest) (*ListSessionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjectSessions not implemented")
}
func (UnimplementedWorkspaceServiceServer) mustEmbedUnimplementedWorkspaceServiceServer() {}
func (UnimplementedWorkspaceServiceServer) testEmbeddedByValue()                          {}

// UnsafeWorkspaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceServiceServer will
// result in compilation errors.
type UnsafeWorkspaceServiceServer interface {
	mustEmbedUnimplementedWorkspaceServiceServer()
}

func RegisterWorkspaceServiceServer(s grpc.ServiceRegistrar, srv WorkspaceServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkspaceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceService_ServiceDesc, srv)
}

func _WorkspaceService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_AddProjectMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).AddProjectMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_AddProjectMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).AddProjectMember(ctx, req.(*AddProjectMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_RemoveProjectMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProjectMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).RemoveProjectMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_RemoveProjectMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).RemoveProjectMember(ctx, req.(*RemoveProjectMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetFeatureTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeatureTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetFeatureTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetFeatureTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetFeatureTree(ctx, req.(*GetFeatureTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_CreateFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateFeature(ctx, req.(*CreateFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_CreateFeatureGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeatureGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateFeatureGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateFeatureGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateFeatureGroup(ctx, req.(*CreateFeatureGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetFeature(ctx, req.(*GetFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_UpdateFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).UpdateFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_UpdateFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).UpdateFeature(ctx, req.(*UpdateFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_DeleteFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).DeleteFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_DeleteFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).DeleteFeature(ctx, req.(*DeleteFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_CreateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateDocument(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListDocumentSections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentSectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListDocumentSections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListDocumentSections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListDocumentSections(ctx, req.(*ListDocumentSectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetDocumentSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetDocumentSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetDocumentSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetDocumentSection(ctx, req.(*GetDocumentSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_CreateDocumentSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateDocumentSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateDocumentSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateDocumentSection(ctx, req.(*CreateDocumentSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_UpdateDocumentSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).UpdateDocumentSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_UpdateDocumentSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).UpdateDocumentSection(ctx, req.(*UpdateDocumentSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_UpdateDocumentSectionContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentSectionContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).UpdateDocumentSectionContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_UpdateDocumentSectionContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).UpdateDocumentSectionContent(ctx, req.(*UpdateDocumentSectionContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_CreateDocumentSectionVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentSectionVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateDocumentSectionVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateDocumentSectionVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateDocumentSectionVersion(ctx, req.(*CreateDocumentSectionVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListDocumentSectionVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentSectionVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListDocumentSectionVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListDocumentSectionVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListDocumentSectionVersions(ctx, req.(*ListDocumentSectionVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetCurrentDocumentSectionVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentDocumentSectionVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetCurrentDocumentSectionVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetCurrentDocumentSectionVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetCurrentDocumentSectionVersion(ctx, req.(*GetCurrentDocumentSectionVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_SetCurrentDocumentSectionVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCurrentDocumentSectionVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).SetCurrentDocumentSectionVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_SetCurrentDocumentSectionVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).SetCurrentDocumentSectionVersion(ctx, req.(*SetCurrentDocumentSectionVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListChatMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListChatMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListChatMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListChatMessages(ctx, req.(*ListChatMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_AppendChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendChatMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).AppendChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_AppendChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).AppendChatMessage(ctx, req.(*AppendChatMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_UpdateSessionContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).UpdateSessionContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_UpdateSessionContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).UpdateSessionContext(ctx, req.(*UpdateSessionContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListProjectSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListProjectSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListProjectSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListProjectSessions(ctx, req.(*ListProjectSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceService_ServiceDesc is the grpc.ServiceDesc for WorkspaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workspace.v1.WorkspaceService",
	HandlerType: (*WorkspaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _WorkspaceService_CreateProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _WorkspaceService_ListProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _WorkspaceService_GetProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _WorkspaceService_UpdateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _WorkspaceService_DeleteProject_Handler,
		},
		{
			MethodName: "AddProjectMember",
			Handler:    _WorkspaceService_AddProjectMember_Handler,
		},
		{
			MethodName: "RemoveProjectMember",
			Handler:    _WorkspaceService_RemoveProjectMember_Handler,
		},
		{
			MethodName: "GetFeatureTree",
			Handler:    _WorkspaceService_GetFeatureTree_Handler,
		},
		{
			MethodName: "CreateFeature",
			Handler:    _WorkspaceService_CreateFeature_Handler,
		},
		{
			MethodName: "CreateFeatureGroup",
			Handler:    _WorkspaceService_CreateFeatureGroup_Handler,
		},
		{
			MethodName: "GetFeature",
			Handler:    _WorkspaceService_GetFeature_Handler,
		},
		{
			MethodName: "UpdateFeature",
			Handler:    _WorkspaceService_UpdateFeature_Handler,
		},
		{
			MethodName: "DeleteFeature",
			Handler:    _WorkspaceService_DeleteFeature_Handler,
		},
		{
			MethodName: "CreateDocument",
			Handler:    _WorkspaceService_CreateDocument_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _WorkspaceService_ListDocuments_Handler,
		},
		{
			MethodName: "ListDocumentSections",
			Handler:    _WorkspaceService_ListDocumentSections_Handler,
		},
		{
			MethodName: "GetDocumentSection",
			Handler:    _WorkspaceService_GetDocumentSection_Handler,
		},
		{
			MethodName: "CreateDocumentSection",
			Handler:    _WorkspaceService_CreateDocumentSection_Handler,
		},
		{
			MethodName: "UpdateDocumentSection",
			Handler:    _WorkspaceService_UpdateDocumentSection_Handler,
		},
		{
			MethodName: "UpdateDocumentSectionContent",
			Handler:    _WorkspaceService_UpdateDocumentSectionContent_Handler,
		},
		{
			MethodName: "CreateDocumentSectionVersion",
			Handler:    _WorkspaceService_CreateDocumentSectionVersion_Handler,
		},
		{
			MethodName: "ListDocumentSectionVersions",
			Handler:    _WorkspaceService_ListDocumentSectionVersions_Handler,
		},
		{
			MethodName: "GetCurrentDocumentSectionVersion",
			Handler:    _WorkspaceService_GetCurrentDocumentSectionVersion_Handler,
		},
		{
			MethodName: "SetCurrentDocumentSectionVersion",
			Handler:    _WorkspaceService_SetCurrentDocumentSectionVersion_Handler,
		},
		{
			MethodName: "ListChatMessages",
			Handler:    _WorkspaceService_ListChatMessages_Handler,
		},
		{
			MethodName: "AppendChatMessage",
			Handler:    _WorkspaceService_AppendChatMessage_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _WorkspaceService_CreateSession_Handler,
		},
		{
			MethodName: "UpdateSessionContext",
			Handler:    _WorkspaceService_UpdateSessionContext_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _WorkspaceService_GetSession_Handler,
		},
		{
			MethodName: "ListProjectSessions",
			Handler:    _WorkspaceService_ListProjectSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workspace/workspace.proto",
}
