// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: author/authorization.proto

package author

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,4,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterPayload) Reset() {
	*x = FilterPayload{}
	mi := &file_author_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterPayload) ProtoMessage() {}

func (x *FilterPayload) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterPayload.ProtoReflect.Descriptor instead.
func (*FilterPayload) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *FilterPayload) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *FilterPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FilterPayload) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *FilterPayload) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_author_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pagination) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TenantPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=author.v1.Status" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPayload) Reset() {
	*x = TenantPayload{}
	mi := &file_author_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPayload) ProtoMessage() {}

func (x *TenantPayload) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPayload.ProtoReflect.Descriptor instead.
func (*TenantPayload) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *TenantPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TenantPayload) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_INACTIVE
}

func (x *TenantPayload) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TenantPayload) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type RolePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=author.v1.Status" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePayload) Reset() {
	*x = RolePayload{}
	mi := &file_author_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePayload) ProtoMessage() {}

func (x *RolePayload) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePayload.ProtoReflect.Descriptor instead.
func (*RolePayload) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *RolePayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RolePayload) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RolePayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RolePayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RolePayload) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_INACTIVE
}

func (x *RolePayload) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RolePayload) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type PermissionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=author.v1.Status" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionPayload) Reset() {
	*x = PermissionPayload{}
	mi := &file_author_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionPayload) ProtoMessage() {}

func (x *PermissionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionPayload.ProtoReflect.Descriptor instead.
func (*PermissionPayload) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PermissionPayload) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *PermissionPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PermissionPayload) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_INACTIVE
}

func (x *PermissionPayload) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PermissionPayload) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type SearchPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *FilterPayload         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPayload) Reset() {
	*x = SearchPayload{}
	mi := &file_author_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPayload) ProtoMessage() {}

func (x *SearchPayload) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPayload.ProtoReflect.Descriptor instead.
func (*SearchPayload) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *SearchPayload) GetFilter() *FilterPayload {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchPayload) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type RolePermissionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionPayload) Reset() {
	*x = RolePermissionPayload{}
	mi := &file_author_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionPayload) ProtoMessage() {}

func (x *RolePermissionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionPayload.ProtoReflect.Descriptor instead.
func (*RolePermissionPayload) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{6}
}

func (x *RolePermissionPayload) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RolePermissionPayload) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type RolePermissionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RolePayload           `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Permissions   []*PermissionPayload   `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionData) Reset() {
	*x = RolePermissionData{}
	mi := &file_author_authorization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionData) ProtoMessage() {}

func (x *RolePermissionData) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionData.ProtoReflect.Descriptor instead.
func (*RolePermissionData) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{7}
}

func (x *RolePermissionData) GetRole() *RolePayload {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RolePermissionData) GetPermissions() []*PermissionPayload {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// =======================
// Requests
// =======================
type TenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload       *TenantPayload         `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantRequest) Reset() {
	*x = TenantRequest{}
	mi := &file_author_authorization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRequest) ProtoMessage() {}

func (x *TenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantRequest.ProtoReflect.Descriptor instead.
func (*TenantRequest) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{8}
}

func (x *TenantRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TenantRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TenantRequest) GetPayload() *TenantPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantRequest) Reset() {
	*x = ListTenantRequest{}
	mi := &file_author_authorization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantRequest) ProtoMessage() {}

func (x *ListTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantRequest.ProtoReflect.Descriptor instead.
func (*ListTenantRequest) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{9}
}

func (x *ListTenantRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListTenantRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ListTenantRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type RoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload       *RolePayload           `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleRequest) Reset() {
	*x = RoleRequest{}
	mi := &file_author_authorization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRequest) ProtoMessage() {}

func (x *RoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRequest.ProtoReflect.Descriptor instead.
func (*RoleRequest) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{10}
}

func (x *RoleRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RoleRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RoleRequest) GetPayload() *RolePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRequest) Reset() {
	*x = ListRoleRequest{}
	mi := &file_author_authorization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRequest) ProtoMessage() {}

func (x *ListRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRequest.ProtoReflect.Descriptor instead.
func (*ListRoleRequest) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{11}
}

func (x *ListRoleRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListRoleRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ListRoleRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload       *PermissionPayload     `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionRequest) Reset() {
	*x = PermissionRequest{}
	mi := &file_author_authorization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRequest) ProtoMessage() {}

func (x *PermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRequest.ProtoReflect.Descriptor instead.
func (*PermissionRequest) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{12}
}

func (x *PermissionRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PermissionRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PermissionRequest) GetPayload() *PermissionPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionRequest) Reset() {
	*x = ListPermissionRequest{}
	mi := &file_author_authorization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionRequest) ProtoMessage() {}

func (x *ListPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionRequest) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{13}
}

func (x *ListPermissionRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListPermissionRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ListPermissionRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload       *SearchPayload         `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_author_authorization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{14}
}

func (x *SearchRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SearchRequest) GetPayload() *SearchPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RolePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload       *RolePermissionPayload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionRequest) Reset() {
	*x = RolePermissionRequest{}
	mi := &file_author_authorization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionRequest) ProtoMessage() {}

func (x *RolePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionRequest.ProtoReflect.Descriptor instead.
func (*RolePermissionRequest) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{15}
}

func (x *RolePermissionRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RolePermissionRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RolePermissionRequest) GetPayload() *RolePermissionPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// =======================
// Responses
// =======================
type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Payload       *TenantPayload         `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_author_authorization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{16}
}

func (x *TenantResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TenantResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TenantResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TenantResponse) GetPayload() *TenantPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Payload       []*TenantPayload       `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter        *FilterPayload         `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantResponse) Reset() {
	*x = ListTenantResponse{}
	mi := &file_author_authorization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantResponse) ProtoMessage() {}

func (x *ListTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantResponse.ProtoReflect.Descriptor instead.
func (*ListTenantResponse) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{17}
}

func (x *ListTenantResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListTenantResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ListTenantResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListTenantResponse) GetPayload() []*TenantPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ListTenantResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTenantResponse) GetFilter() *FilterPayload {
	if x != nil {
		return x.Filter
	}
	return nil
}

type RoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Payload       *RolePayload           `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponse) Reset() {
	*x = RoleResponse{}
	mi := &file_author_authorization_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponse) ProtoMessage() {}

func (x *RoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponse.ProtoReflect.Descriptor instead.
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{18}
}

func (x *RoleResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RoleResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RoleResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RoleResponse) GetPayload() *RolePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Payload       []*RolePayload         `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter        *FilterPayload         `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleResponse) Reset() {
	*x = ListRoleResponse{}
	mi := &file_author_authorization_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleResponse) ProtoMessage() {}

func (x *ListRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleResponse.ProtoReflect.Descriptor instead.
func (*ListRoleResponse) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{19}
}

func (x *ListRoleResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListRoleResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ListRoleResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListRoleResponse) GetPayload() []*RolePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ListRoleResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListRoleResponse) GetFilter() *FilterPayload {
	if x != nil {
		return x.Filter
	}
	return nil
}

type PermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Payload       *PermissionPayload     `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResponse) Reset() {
	*x = PermissionResponse{}
	mi := &file_author_authorization_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResponse) ProtoMessage() {}

func (x *PermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResponse.ProtoReflect.Descriptor instead.
func (*PermissionResponse) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{20}
}

func (x *PermissionResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PermissionResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PermissionResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PermissionResponse) GetPayload() *PermissionPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Payload       []*PermissionPayload   `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter        *FilterPayload         `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionResponse) Reset() {
	*x = ListPermissionResponse{}
	mi := &file_author_authorization_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionResponse) ProtoMessage() {}

func (x *ListPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionResponse) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{21}
}

func (x *ListPermissionResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListPermissionResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ListPermissionResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListPermissionResponse) GetPayload() []*PermissionPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ListPermissionResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPermissionResponse) GetFilter() *FilterPayload {
	if x != nil {
		return x.Filter
	}
	return nil
}

type RolePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Payload       *RolePermissionData    `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter        *FilterPayload         `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionResponse) Reset() {
	*x = RolePermissionResponse{}
	mi := &file_author_authorization_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionResponse) ProtoMessage() {}

func (x *RolePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionResponse.ProtoReflect.Descriptor instead.
func (*RolePermissionResponse) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{22}
}

func (x *RolePermissionResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RolePermissionResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RolePermissionResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RolePermissionResponse) GetPayload() *RolePermissionData {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RolePermissionResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *RolePermissionResponse) GetFilter() *FilterPayload {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListRolePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Payload       []*RolePermissionData  `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter        *FilterPayload         `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolePermissionResponse) Reset() {
	*x = ListRolePermissionResponse{}
	mi := &file_author_authorization_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolePermissionResponse) ProtoMessage() {}

func (x *ListRolePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_authorization_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolePermissionResponse.ProtoReflect.Descriptor instead.
func (*ListRolePermissionResponse) Descriptor() ([]byte, []int) {
	return file_author_authorization_proto_rawDescGZIP(), []int{23}
}

func (x *ListRolePermissionResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListRolePermissionResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ListRolePermissionResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListRolePermissionResponse) GetPayload() []*RolePermissionData {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ListRolePermissionResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListRolePermissionResponse) GetFilter() *FilterPayload {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_author_authorization_proto protoreflect.FileDescriptor

const file_author_authorization_proto_rawDesc = "" +
	"\n" +
	"\x1aauthor/authorization.proto\x12\tauthor.v1\x1a\x11author/base.proto\"\x84\x01\n" +
	"\rFilterPayload\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12#\n" +
	"\rpermission_id\x18\x04 \x01(\tR\fpermissionId\"L\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"\xcb\x01\n" +
	"\rTenantPayload\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.author.v1.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\xe2\x01\n" +
	"\vRolePayload\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12)\n" +
	"\x06status\x18\x05 \x01(\x0e2\x11.author.v1.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\xf4\x01\n" +
	"\x11PermissionPayload\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12)\n" +
	"\x06status\x18\x05 \x01(\x0e2\x11.author.v1.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"x\n" +
	"\rSearchPayload\x120\n" +
	"\x06filter\x18\x01 \x01(\v2\x18.author.v1.FilterPayloadR\x06filter\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.author.v1.PaginationR\n" +
	"pagination\"R\n" +
	"\x15RolePermissionPayload\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"\x80\x01\n" +
	"\x12RolePermissionData\x12*\n" +
	"\x04role\x18\x01 \x01(\v2\x16.author.v1.RolePayloadR\x04role\x12>\n" +
	"\vpermissions\x18\x02 \x03(\v2\x1c.author.v1.PermissionPayloadR\vpermissions\"\xa8\x01\n" +
	"\rTenantRequest\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x122\n" +
	"\apayload\x18\x03 \x01(\v2\x18.author.v1.TenantPayloadR\apayload\"\xaf\x01\n" +
	"\x11ListTenantRequest\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x125\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x15.author.v1.PaginationR\n" +
	"pagination\"\xa4\x01\n" +
	"\vRoleRequest\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x120\n" +
	"\apayload\x18\x03 \x01(\v2\x16.author.v1.RolePayloadR\apayload\"\xad\x01\n" +
	"\x0fListRoleRequest\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x125\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x15.author.v1.PaginationR\n" +
	"pagination\"\xb0\x01\n" +
	"\x11PermissionRequest\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x126\n" +
	"\apayload\x18\x03 \x01(\v2\x1c.author.v1.PermissionPayloadR\apayload\"\xb3\x01\n" +
	"\x15ListPermissionRequest\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x125\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x15.author.v1.PaginationR\n" +
	"pagination\"\xa8\x01\n" +
	"\rSearchRequest\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x122\n" +
	"\apayload\x18\x03 \x01(\v2\x18.author.v1.SearchPayloadR\apayload\"\xb8\x01\n" +
	"\x15RolePermissionRequest\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x12:\n" +
	"\apayload\x18\x03 \x01(\v2 .author.v1.RolePermissionPayloadR\apayload\"\xd4\x01\n" +
	"\x0eTenantResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\x11.author.v1.ResultR\x06result\x122\n" +
	"\apayload\x18\x04 \x01(\v2\x18.author.v1.TenantPayloadR\apayload\"\xc1\x02\n" +
	"\x12ListTenantResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\x11.author.v1.ResultR\x06result\x122\n" +
	"\apayload\x18\x04 \x03(\v2\x18.author.v1.TenantPayloadR\apayload\x125\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x15.author.v1.PaginationR\n" +
	"pagination\x120\n" +
	"\x06filter\x18\x06 \x01(\v2\x18.author.v1.FilterPayloadR\x06filter\"\xd0\x01\n" +
	"\fRoleResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\x11.author.v1.ResultR\x06result\x120\n" +
	"\apayload\x18\x04 \x01(\v2\x16.author.v1.RolePayloadR\apayload\"\xbd\x02\n" +
	"\x10ListRoleResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\x11.author.v1.ResultR\x06result\x120\n" +
	"\apayload\x18\x04 \x03(\v2\x16.author.v1.RolePayloadR\apayload\x125\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x15.author.v1.PaginationR\n" +
	"pagination\x120\n" +
	"\x06filter\x18\x06 \x01(\v2\x18.author.v1.FilterPayloadR\x06filter\"\xdc\x01\n" +
	"\x12PermissionResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\x11.author.v1.ResultR\x06result\x126\n" +
	"\apayload\x18\x04 \x01(\v2\x1c.author.v1.PermissionPayloadR\apayload\"\xc9\x02\n" +
	"\x16ListPermissionResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\x11.author.v1.ResultR\x06result\x126\n" +
	"\apayload\x18\x04 \x03(\v2\x1c.author.v1.PermissionPayloadR\apayload\x125\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x15.author.v1.PaginationR\n" +
	"pagination\x120\n" +
	"\x06filter\x18\x06 \x01(\v2\x18.author.v1.FilterPayloadR\x06filter\"\xca\x02\n" +
	"\x16RolePermissionResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\x11.author.v1.ResultR\x06result\x127\n" +
	"\apayload\x18\x04 \x01(\v2\x1d.author.v1.RolePermissionDataR\apayload\x125\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x15.author.v1.PaginationR\n" +
	"pagination\x120\n" +
	"\x06filter\x18\x06 \x01(\v2\x18.author.v1.FilterPayloadR\x06filter\"\xce\x02\n" +
	"\x1aListRolePermissionResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.author.v1.MetadataR\bmetadata\x122\n" +
	"\tsignature\x18\x02 \x01(\v2\x14.author.v1.SignatureR\tsignature\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\x11.author.v1.ResultR\x06result\x127\n" +
	"\apayload\x18\x04 \x03(\v2\x1d.author.v1.RolePermissionDataR\apayload\x125\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x15.author.v1.PaginationR\n" +
	"pagination\x120\n" +
	"\x06filter\x18\x06 \x01(\v2\x18.author.v1.FilterPayloadR\x06filter2\x8f\r\n" +
	"\x14AuthorizationService\x12C\n" +
	"\fCreateTenant\x12\x18.author.v1.TenantRequest\x1a\x19.author.v1.TenantResponse\x12C\n" +
	"\fUpdateTenant\x12\x18.author.v1.TenantRequest\x1a\x19.author.v1.TenantResponse\x12C\n" +
	"\fDeleteTenant\x12\x18.author.v1.TenantRequest\x1a\x19.author.v1.TenantResponse\x12@\n" +
	"\tGetTenant\x12\x18.author.v1.TenantRequest\x1a\x19.author.v1.TenantResponse\x12I\n" +
	"\n" +
	"ListTenant\x12\x1c.author.v1.ListTenantRequest\x1a\x1d.author.v1.ListTenantResponse\x12G\n" +
	"\fSearchTenant\x12\x18.author.v1.SearchRequest\x1a\x1d.author.v1.ListTenantResponse\x12=\n" +
	"\n" +
	"CreateRole\x12\x16.author.v1.RoleRequest\x1a\x17.author.v1.RoleResponse\x12=\n" +
	"\n" +
	"UpdateRole\x12\x16.author.v1.RoleRequest\x1a\x17.author.v1.RoleResponse\x12=\n" +
	"\n" +
	"DeleteRole\x12\x16.author.v1.RoleRequest\x1a\x17.author.v1.RoleResponse\x12:\n" +
	"\aGetRole\x12\x16.author.v1.RoleRequest\x1a\x17.author.v1.RoleResponse\x12C\n" +
	"\bListRole\x12\x1a.author.v1.ListRoleRequest\x1a\x1b.author.v1.ListRoleResponse\x12C\n" +
	"\n" +
	"SearchRole\x12\x18.author.v1.SearchRequest\x1a\x1b.author.v1.ListRoleResponse\x12O\n" +
	"\x10CreatePermission\x12\x1c.author.v1.PermissionRequest\x1a\x1d.author.v1.PermissionResponse\x12O\n" +
	"\x10UpdatePermission\x12\x1c.author.v1.PermissionRequest\x1a\x1d.author.v1.PermissionResponse\x12O\n" +
	"\x10DeletePermission\x12\x1c.author.v1.PermissionRequest\x1a\x1d.author.v1.PermissionResponse\x12L\n" +
	"\rGetPermission\x12\x1c.author.v1.PermissionRequest\x1a\x1d.author.v1.PermissionResponse\x12U\n" +
	"\x0eListPermission\x12 .author.v1.ListPermissionRequest\x1a!.author.v1.ListPermissionResponse\x12O\n" +
	"\x10SearchPermission\x12\x18.author.v1.SearchRequest\x1a!.author.v1.ListPermissionResponse\x12W\n" +
	"\x10AssignPermission\x12 .author.v1.RolePermissionRequest\x1a!.author.v1.RolePermissionResponse\x12Y\n" +
	"\x12UnassignPermission\x12 .author.v1.RolePermissionRequest\x1a!.author.v1.RolePermissionResponse\x12Y\n" +
	"\x12OverridePermission\x12 .author.v1.RolePermissionRequest\x1a!.author.v1.RolePermissionResponse\x12W\n" +
	"\x14SearchRolePermission\x12\x18.author.v1.SearchRequest\x1a%.author.v1.ListRolePermissionResponseBP\n" +
	"\x1ecom.blcvn.kratos.protos.authorZ.github.com/blcvn/kratos-proto/go/author;authorb\x06proto3"

var (
	file_author_authorization_proto_rawDescOnce sync.Once
	file_author_authorization_proto_rawDescData []byte
)

func file_author_authorization_proto_rawDescGZIP() []byte {
	file_author_authorization_proto_rawDescOnce.Do(func() {
		file_author_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_author_authorization_proto_rawDesc), len(file_author_authorization_proto_rawDesc)))
	})
	return file_author_authorization_proto_rawDescData
}

var file_author_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_author_authorization_proto_goTypes = []any{
	(*FilterPayload)(nil),              // 0: author.v1.FilterPayload
	(*Pagination)(nil),                 // 1: author.v1.Pagination
	(*TenantPayload)(nil),              // 2: author.v1.TenantPayload
	(*RolePayload)(nil),                // 3: author.v1.RolePayload
	(*PermissionPayload)(nil),          // 4: author.v1.PermissionPayload
	(*SearchPayload)(nil),              // 5: author.v1.SearchPayload
	(*RolePermissionPayload)(nil),      // 6: author.v1.RolePermissionPayload
	(*RolePermissionData)(nil),         // 7: author.v1.RolePermissionData
	(*TenantRequest)(nil),              // 8: author.v1.TenantRequest
	(*ListTenantRequest)(nil),          // 9: author.v1.ListTenantRequest
	(*RoleRequest)(nil),                // 10: author.v1.RoleRequest
	(*ListRoleRequest)(nil),            // 11: author.v1.ListRoleRequest
	(*PermissionRequest)(nil),          // 12: author.v1.PermissionRequest
	(*ListPermissionRequest)(nil),      // 13: author.v1.ListPermissionRequest
	(*SearchRequest)(nil),              // 14: author.v1.SearchRequest
	(*RolePermissionRequest)(nil),      // 15: author.v1.RolePermissionRequest
	(*TenantResponse)(nil),             // 16: author.v1.TenantResponse
	(*ListTenantResponse)(nil),         // 17: author.v1.ListTenantResponse
	(*RoleResponse)(nil),               // 18: author.v1.RoleResponse
	(*ListRoleResponse)(nil),           // 19: author.v1.ListRoleResponse
	(*PermissionResponse)(nil),         // 20: author.v1.PermissionResponse
	(*ListPermissionResponse)(nil),     // 21: author.v1.ListPermissionResponse
	(*RolePermissionResponse)(nil),     // 22: author.v1.RolePermissionResponse
	(*ListRolePermissionResponse)(nil), // 23: author.v1.ListRolePermissionResponse
	(Status)(0),                        // 24: author.v1.Status
	(*Metadata)(nil),                   // 25: author.v1.Metadata
	(*Signature)(nil),                  // 26: author.v1.Signature
	(*Result)(nil),                     // 27: author.v1.Result
}
var file_author_authorization_proto_depIdxs = []int32{
	24, // 0: author.v1.TenantPayload.status:type_name -> author.v1.Status
	24, // 1: author.v1.RolePayload.status:type_name -> author.v1.Status
	24, // 2: author.v1.PermissionPayload.status:type_name -> author.v1.Status
	0,  // 3: author.v1.SearchPayload.filter:type_name -> author.v1.FilterPayload
	1,  // 4: author.v1.SearchPayload.pagination:type_name -> author.v1.Pagination
	3,  // 5: author.v1.RolePermissionData.role:type_name -> author.v1.RolePayload
	4,  // 6: author.v1.RolePermissionData.permissions:type_name -> author.v1.PermissionPayload
	25, // 7: author.v1.TenantRequest.metadata:type_name -> author.v1.Metadata
	26, // 8: author.v1.TenantRequest.signature:type_name -> author.v1.Signature
	2,  // 9: author.v1.TenantRequest.payload:type_name -> author.v1.TenantPayload
	25, // 10: author.v1.ListTenantRequest.metadata:type_name -> author.v1.Metadata
	26, // 11: author.v1.ListTenantRequest.signature:type_name -> author.v1.Signature
	1,  // 12: author.v1.ListTenantRequest.pagination:type_name -> author.v1.Pagination
	25, // 13: author.v1.RoleRequest.metadata:type_name -> author.v1.Metadata
	26, // 14: author.v1.RoleRequest.signature:type_name -> author.v1.Signature
	3,  // 15: author.v1.RoleRequest.payload:type_name -> author.v1.RolePayload
	25, // 16: author.v1.ListRoleRequest.metadata:type_name -> author.v1.Metadata
	26, // 17: author.v1.ListRoleRequest.signature:type_name -> author.v1.Signature
	1,  // 18: author.v1.ListRoleRequest.pagination:type_name -> author.v1.Pagination
	25, // 19: author.v1.PermissionRequest.metadata:type_name -> author.v1.Metadata
	26, // 20: author.v1.PermissionRequest.signature:type_name -> author.v1.Signature
	4,  // 21: author.v1.PermissionRequest.payload:type_name -> author.v1.PermissionPayload
	25, // 22: author.v1.ListPermissionRequest.metadata:type_name -> author.v1.Metadata
	26, // 23: author.v1.ListPermissionRequest.signature:type_name -> author.v1.Signature
	1,  // 24: author.v1.ListPermissionRequest.pagination:type_name -> author.v1.Pagination
	25, // 25: author.v1.SearchRequest.metadata:type_name -> author.v1.Metadata
	26, // 26: author.v1.SearchRequest.signature:type_name -> author.v1.Signature
	5,  // 27: author.v1.SearchRequest.payload:type_name -> author.v1.SearchPayload
	25, // 28: author.v1.RolePermissionRequest.metadata:type_name -> author.v1.Metadata
	26, // 29: author.v1.RolePermissionRequest.signature:type_name -> author.v1.Signature
	6,  // 30: author.v1.RolePermissionRequest.payload:type_name -> author.v1.RolePermissionPayload
	25, // 31: author.v1.TenantResponse.metadata:type_name -> author.v1.Metadata
	26, // 32: author.v1.TenantResponse.signature:type_name -> author.v1.Signature
	27, // 33: author.v1.TenantResponse.result:type_name -> author.v1.Result
	2,  // 34: author.v1.TenantResponse.payload:type_name -> author.v1.TenantPayload
	25, // 35: author.v1.ListTenantResponse.metadata:type_name -> author.v1.Metadata
	26, // 36: author.v1.ListTenantResponse.signature:type_name -> author.v1.Signature
	27, // 37: author.v1.ListTenantResponse.result:type_name -> author.v1.Result
	2,  // 38: author.v1.ListTenantResponse.payload:type_name -> author.v1.TenantPayload
	1,  // 39: author.v1.ListTenantResponse.pagination:type_name -> author.v1.Pagination
	0,  // 40: author.v1.ListTenantResponse.filter:type_name -> author.v1.FilterPayload
	25, // 41: author.v1.RoleResponse.metadata:type_name -> author.v1.Metadata
	26, // 42: author.v1.RoleResponse.signature:type_name -> author.v1.Signature
	27, // 43: author.v1.RoleResponse.result:type_name -> author.v1.Result
	3,  // 44: author.v1.RoleResponse.payload:type_name -> author.v1.RolePayload
	25, // 45: author.v1.ListRoleResponse.metadata:type_name -> author.v1.Metadata
	26, // 46: author.v1.ListRoleResponse.signature:type_name -> author.v1.Signature
	27, // 47: author.v1.ListRoleResponse.result:type_name -> author.v1.Result
	3,  // 48: author.v1.ListRoleResponse.payload:type_name -> author.v1.RolePayload
	1,  // 49: author.v1.ListRoleResponse.pagination:type_name -> author.v1.Pagination
	0,  // 50: author.v1.ListRoleResponse.filter:type_name -> author.v1.FilterPayload
	25, // 51: author.v1.PermissionResponse.metadata:type_name -> author.v1.Metadata
	26, // 52: author.v1.PermissionResponse.signature:type_name -> author.v1.Signature
	27, // 53: author.v1.PermissionResponse.result:type_name -> author.v1.Result
	4,  // 54: author.v1.PermissionResponse.payload:type_name -> author.v1.PermissionPayload
	25, // 55: author.v1.ListPermissionResponse.metadata:type_name -> author.v1.Metadata
	26, // 56: author.v1.ListPermissionResponse.signature:type_name -> author.v1.Signature
	27, // 57: author.v1.ListPermissionResponse.result:type_name -> author.v1.Result
	4,  // 58: author.v1.ListPermissionResponse.payload:type_name -> author.v1.PermissionPayload
	1,  // 59: author.v1.ListPermissionResponse.pagination:type_name -> author.v1.Pagination
	0,  // 60: author.v1.ListPermissionResponse.filter:type_name -> author.v1.FilterPayload
	25, // 61: author.v1.RolePermissionResponse.metadata:type_name -> author.v1.Metadata
	26, // 62: author.v1.RolePermissionResponse.signature:type_name -> author.v1.Signature
	27, // 63: author.v1.RolePermissionResponse.result:type_name -> author.v1.Result
	7,  // 64: author.v1.RolePermissionResponse.payload:type_name -> author.v1.RolePermissionData
	1,  // 65: author.v1.RolePermissionResponse.pagination:type_name -> author.v1.Pagination
	0,  // 66: author.v1.RolePermissionResponse.filter:type_name -> author.v1.FilterPayload
	25, // 67: author.v1.ListRolePermissionResponse.metadata:type_name -> author.v1.Metadata
	26, // 68: author.v1.ListRolePermissionResponse.signature:type_name -> author.v1.Signature
	27, // 69: author.v1.ListRolePermissionResponse.result:type_name -> author.v1.Result
	7,  // 70: author.v1.ListRolePermissionResponse.payload:type_name -> author.v1.RolePermissionData
	1,  // 71: author.v1.ListRolePermissionResponse.pagination:type_name -> author.v1.Pagination
	0,  // 72: author.v1.ListRolePermissionResponse.filter:type_name -> author.v1.FilterPayload
	8,  // 73: author.v1.AuthorizationService.CreateTenant:input_type -> author.v1.TenantRequest
	8,  // 74: author.v1.AuthorizationService.UpdateTenant:input_type -> author.v1.TenantRequest
	8,  // 75: author.v1.AuthorizationService.DeleteTenant:input_type -> author.v1.TenantRequest
	8,  // 76: author.v1.AuthorizationService.GetTenant:input_type -> author.v1.TenantRequest
	9,  // 77: author.v1.AuthorizationService.ListTenant:input_type -> author.v1.ListTenantRequest
	14, // 78: author.v1.AuthorizationService.SearchTenant:input_type -> author.v1.SearchRequest
	10, // 79: author.v1.AuthorizationService.CreateRole:input_type -> author.v1.RoleRequest
	10, // 80: author.v1.AuthorizationService.UpdateRole:input_type -> author.v1.RoleRequest
	10, // 81: author.v1.AuthorizationService.DeleteRole:input_type -> author.v1.RoleRequest
	10, // 82: author.v1.AuthorizationService.GetRole:input_type -> author.v1.RoleRequest
	11, // 83: author.v1.AuthorizationService.ListRole:input_type -> author.v1.ListRoleRequest
	14, // 84: author.v1.AuthorizationService.SearchRole:input_type -> author.v1.SearchRequest
	12, // 85: author.v1.AuthorizationService.CreatePermission:input_type -> author.v1.PermissionRequest
	12, // 86: author.v1.AuthorizationService.UpdatePermission:input_type -> author.v1.PermissionRequest
	12, // 87: author.v1.AuthorizationService.DeletePermission:input_type -> author.v1.PermissionRequest
	12, // 88: author.v1.AuthorizationService.GetPermission:input_type -> author.v1.PermissionRequest
	13, // 89: author.v1.AuthorizationService.ListPermission:input_type -> author.v1.ListPermissionRequest
	14, // 90: author.v1.AuthorizationService.SearchPermission:input_type -> author.v1.SearchRequest
	15, // 91: author.v1.AuthorizationService.AssignPermission:input_type -> author.v1.RolePermissionRequest
	15, // 92: author.v1.AuthorizationService.UnassignPermission:input_type -> author.v1.RolePermissionRequest
	15, // 93: author.v1.AuthorizationService.OverridePermission:input_type -> author.v1.RolePermissionRequest
	14, // 94: author.v1.AuthorizationService.SearchRolePermission:input_type -> author.v1.SearchRequest
	16, // 95: author.v1.AuthorizationService.CreateTenant:output_type -> author.v1.TenantResponse
	16, // 96: author.v1.AuthorizationService.UpdateTenant:output_type -> author.v1.TenantResponse
	16, // 97: author.v1.AuthorizationService.DeleteTenant:output_type -> author.v1.TenantResponse
	16, // 98: author.v1.AuthorizationService.GetTenant:output_type -> author.v1.TenantResponse
	17, // 99: author.v1.AuthorizationService.ListTenant:output_type -> author.v1.ListTenantResponse
	17, // 100: author.v1.AuthorizationService.SearchTenant:output_type -> author.v1.ListTenantResponse
	18, // 101: author.v1.AuthorizationService.CreateRole:output_type -> author.v1.RoleResponse
	18, // 102: author.v1.AuthorizationService.UpdateRole:output_type -> author.v1.RoleResponse
	18, // 103: author.v1.AuthorizationService.DeleteRole:output_type -> author.v1.RoleResponse
	18, // 104: author.v1.AuthorizationService.GetRole:output_type -> author.v1.RoleResponse
	19, // 105: author.v1.AuthorizationService.ListRole:output_type -> author.v1.ListRoleResponse
	19, // 106: author.v1.AuthorizationService.SearchRole:output_type -> author.v1.ListRoleResponse
	20, // 107: author.v1.AuthorizationService.CreatePermission:output_type -> author.v1.PermissionResponse
	20, // 108: author.v1.AuthorizationService.UpdatePermission:output_type -> author.v1.PermissionResponse
	20, // 109: author.v1.AuthorizationService.DeletePermission:output_type -> author.v1.PermissionResponse
	20, // 110: author.v1.AuthorizationService.GetPermission:output_type -> author.v1.PermissionResponse
	21, // 111: author.v1.AuthorizationService.ListPermission:output_type -> author.v1.ListPermissionResponse
	21, // 112: author.v1.AuthorizationService.SearchPermission:output_type -> author.v1.ListPermissionResponse
	22, // 113: author.v1.AuthorizationService.AssignPermission:output_type -> author.v1.RolePermissionResponse
	22, // 114: author.v1.AuthorizationService.UnassignPermission:output_type -> author.v1.RolePermissionResponse
	22, // 115: author.v1.AuthorizationService.OverridePermission:output_type -> author.v1.RolePermissionResponse
	23, // 116: author.v1.AuthorizationService.SearchRolePermission:output_type -> author.v1.ListRolePermissionResponse
	95, // [95:117] is the sub-list for method output_type
	73, // [73:95] is the sub-list for method input_type
	73, // [73:73] is the sub-list for extension type_name
	73, // [73:73] is the sub-list for extension extendee
	0,  // [0:73] is the sub-list for field type_name
}

func init() { file_author_authorization_proto_init() }
func file_author_authorization_proto_init() {
	if File_author_authorization_proto != nil {
		return
	}
	file_author_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_author_authorization_proto_rawDesc), len(file_author_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_author_authorization_proto_goTypes,
		DependencyIndexes: file_author_authorization_proto_depIdxs,
		MessageInfos:      file_author_authorization_proto_msgTypes,
	}.Build()
	File_author_authorization_proto = out.File
	file_author_authorization_proto_goTypes = nil
	file_author_authorization_proto_depIdxs = nil
}
