// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: ai-agent-registry/ai_agent_registry.proto

package registry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RegistryService_GetPrompt_FullMethodName               = "/registry.v1.RegistryService/GetPrompt"
	RegistryService_GetAgentConfig_FullMethodName          = "/registry.v1.RegistryService/GetAgentConfig"
	RegistryService_GetTemplateConfig_FullMethodName       = "/registry.v1.RegistryService/GetTemplateConfig"
	RegistryService_GetLLMTemperatureConfig_FullMethodName = "/registry.v1.RegistryService/GetLLMTemperatureConfig"
)

// RegistryServiceClient is the client API for RegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryServiceClient interface {
	GetPrompt(ctx context.Context, in *GetPromptRequest, opts ...grpc.CallOption) (*PromptTemplate, error)
	GetAgentConfig(ctx context.Context, in *GetAgentConfigRequest, opts ...grpc.CallOption) (*AgentConfig, error)
	GetTemplateConfig(ctx context.Context, in *GetTemplateConfigRequest, opts ...grpc.CallOption) (*TemplateConfig, error)
	GetLLMTemperatureConfig(ctx context.Context, in *GetLLMTemperatureConfigRequest, opts ...grpc.CallOption) (*LLMTemperatureConfig, error)
}

type registryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryServiceClient(cc grpc.ClientConnInterface) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) GetPrompt(ctx context.Context, in *GetPromptRequest, opts ...grpc.CallOption) (*PromptTemplate, error) {
	out := new(PromptTemplate)
	err := c.cc.Invoke(ctx, RegistryService_GetPrompt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetAgentConfig(ctx context.Context, in *GetAgentConfigRequest, opts ...grpc.CallOption) (*AgentConfig, error) {
	out := new(AgentConfig)
	err := c.cc.Invoke(ctx, RegistryService_GetAgentConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetTemplateConfig(ctx context.Context, in *GetTemplateConfigRequest, opts ...grpc.CallOption) (*TemplateConfig, error) {
	out := new(TemplateConfig)
	err := c.cc.Invoke(ctx, RegistryService_GetTemplateConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetLLMTemperatureConfig(ctx context.Context, in *GetLLMTemperatureConfigRequest, opts ...grpc.CallOption) (*LLMTemperatureConfig, error) {
	out := new(LLMTemperatureConfig)
	err := c.cc.Invoke(ctx, RegistryService_GetLLMTemperatureConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServiceServer is the server API for RegistryService service.
// All implementations must embed UnimplementedRegistryServiceServer
// for forward compatibility
type RegistryServiceServer interface {
	GetPrompt(context.Context, *GetPromptRequest) (*PromptTemplate, error)
	GetAgentConfig(context.Context, *GetAgentConfigRequest) (*AgentConfig, error)
	GetTemplateConfig(context.Context, *GetTemplateConfigRequest) (*TemplateConfig, error)
	GetLLMTemperatureConfig(context.Context, *GetLLMTemperatureConfigRequest) (*LLMTemperatureConfig, error)
	mustEmbedUnimplementedRegistryServiceServer()
}

// UnimplementedRegistryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRegistryServiceServer struct {
}

func (UnimplementedRegistryServiceServer) GetPrompt(context.Context, *GetPromptRequest) (*PromptTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrompt not implemented")
}
func (UnimplementedRegistryServiceServer) GetAgentConfig(context.Context, *GetAgentConfigRequest) (*AgentConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentConfig not implemented")
}
func (UnimplementedRegistryServiceServer) GetTemplateConfig(context.Context, *GetTemplateConfigRequest) (*TemplateConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplateConfig not implemented")
}
func (UnimplementedRegistryServiceServer) GetLLMTemperatureConfig(context.Context, *GetLLMTemperatureConfigRequest) (*LLMTemperatureConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLLMTemperatureConfig not implemented")
}
func (UnimplementedRegistryServiceServer) mustEmbedUnimplementedRegistryServiceServer() {}

// UnsafeRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServiceServer will
// result in compilation errors.
type UnsafeRegistryServiceServer interface {
	mustEmbedUnimplementedRegistryServiceServer()
}

func RegisterRegistryServiceServer(s grpc.ServiceRegistrar, srv RegistryServiceServer) {
	s.RegisterService(&RegistryService_ServiceDesc, srv)
}

func _RegistryService_GetPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetPrompt(ctx, req.(*GetPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetAgentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetAgentConfig(ctx, req.(*GetAgentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetTemplateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetTemplateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetTemplateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetTemplateConfig(ctx, req.(*GetTemplateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetLLMTemperatureConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLLMTemperatureConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetLLMTemperatureConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetLLMTemperatureConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetLLMTemperatureConfig(ctx, req.(*GetLLMTemperatureConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryService_ServiceDesc is the grpc.ServiceDesc for RegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.v1.RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrompt",
			Handler:    _RegistryService_GetPrompt_Handler,
		},
		{
			MethodName: "GetAgentConfig",
			Handler:    _RegistryService_GetAgentConfig_Handler,
		},
		{
			MethodName: "GetTemplateConfig",
			Handler:    _RegistryService_GetTemplateConfig_Handler,
		},
		{
			MethodName: "GetLLMTemperatureConfig",
			Handler:    _RegistryService_GetLLMTemperatureConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai-agent-registry/ai_agent_registry.proto",
}
