// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ai-agent-orchestrator/ai_agent_orchestrator.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SkillRef      string                 `protobuf:"bytes,2,opt,name=skill_ref,json=skillRef,proto3" json:"skill_ref,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	FeatureId     string                 `protobuf:"bytes,4,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	UcId          string                 `protobuf:"bytes,5,opt,name=uc_id,json=ucId,proto3" json:"uc_id,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PerFeature    bool                   `protobuf:"varint,7,opt,name=per_feature,json=perFeature,proto3" json:"per_feature,omitempty"`
	PerUc         bool                   `protobuf:"varint,8,opt,name=per_uc,json=perUc,proto3" json:"per_uc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanStep) Reset() {
	*x = PlanStep{}
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanStep) ProtoMessage() {}

func (x *PlanStep) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanStep.ProtoReflect.Descriptor instead.
func (*PlanStep) Descriptor() ([]byte, []int) {
	return file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *PlanStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanStep) GetSkillRef() string {
	if x != nil {
		return x.SkillRef
	}
	return ""
}

func (x *PlanStep) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *PlanStep) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *PlanStep) GetUcId() string {
	if x != nil {
		return x.UcId
	}
	return ""
}

func (x *PlanStep) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PlanStep) GetPerFeature() bool {
	if x != nil {
		return x.PerFeature
	}
	return false
}

func (x *PlanStep) GetPerUc() bool {
	if x != nil {
		return x.PerUc
	}
	return false
}

type PlanPhase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Steps         []*PlanStep            `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanPhase) Reset() {
	*x = PlanPhase{}
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanPhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanPhase) ProtoMessage() {}

func (x *PlanPhase) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanPhase.ProtoReflect.Descriptor instead.
func (*PlanPhase) Descriptor() ([]byte, []int) {
	return file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *PlanPhase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanPhase) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *PlanPhase) GetSteps() []*PlanStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type ExecutionPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,4,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Phases        []*PlanPhase           `protobuf:"bytes,5,rep,name=phases,proto3" json:"phases,omitempty"`
	FeatureIds    []string               `protobuf:"bytes,6,rep,name=feature_ids,json=featureIds,proto3" json:"feature_ids,omitempty"`
	UcIds         []string               `protobuf:"bytes,7,rep,name=uc_ids,json=ucIds,proto3" json:"uc_ids,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,8,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPlan) Reset() {
	*x = ExecutionPlan{}
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlan) ProtoMessage() {}

func (x *ExecutionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlan.ProtoReflect.Descriptor instead.
func (*ExecutionPlan) Descriptor() ([]byte, []int) {
	return file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionPlan) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecutionPlan) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecutionPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutionPlan) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ExecutionPlan) GetPhases() []*PlanPhase {
	if x != nil {
		return x.Phases
	}
	return nil
}

func (x *ExecutionPlan) GetFeatureIds() []string {
	if x != nil {
		return x.FeatureIds
	}
	return nil
}

func (x *ExecutionPlan) GetUcIds() []string {
	if x != nil {
		return x.UcIds
	}
	return nil
}

func (x *ExecutionPlan) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CreatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Goal          string                 `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	FeatureIds    []string               `protobuf:"bytes,5,rep,name=feature_ids,json=featureIds,proto3" json:"feature_ids,omitempty"`
	UcIds         []string               `protobuf:"bytes,6,rep,name=uc_ids,json=ucIds,proto3" json:"uc_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanRequest) Reset() {
	*x = CreatePlanRequest{}
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanRequest) ProtoMessage() {}

func (x *CreatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanRequest.ProtoReflect.Descriptor instead.
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePlanRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreatePlanRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CreatePlanRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreatePlanRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *CreatePlanRequest) GetFeatureIds() []string {
	if x != nil {
		return x.FeatureIds
	}
	return nil
}

func (x *CreatePlanRequest) GetUcIds() []string {
	if x != nil {
		return x.UcIds
	}
	return nil
}

type RunTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Goal          string                 `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	FeatureIds    []string               `protobuf:"bytes,5,rep,name=feature_ids,json=featureIds,proto3" json:"feature_ids,omitempty"`
	UcIds         []string               `protobuf:"bytes,6,rep,name=uc_ids,json=ucIds,proto3" json:"uc_ids,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskRequest) Reset() {
	*x = RunTaskRequest{}
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskRequest) ProtoMessage() {}

func (x *RunTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskRequest.ProtoReflect.Descriptor instead.
func (*RunTaskRequest) Descriptor() ([]byte, []int) {
	return file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *RunTaskRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RunTaskRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RunTaskRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RunTaskRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *RunTaskRequest) GetFeatureIds() []string {
	if x != nil {
		return x.FeatureIds
	}
	return nil
}

func (x *RunTaskRequest) GetUcIds() []string {
	if x != nil {
		return x.UcIds
	}
	return nil
}

func (x *RunTaskRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type StepStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	SkillId       string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Blocked       bool                   `protobuf:"varint,4,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Document      string                 `protobuf:"bytes,6,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStatus) Reset() {
	*x = StepStatus{}
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStatus) ProtoMessage() {}

func (x *StepStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStatus.ProtoReflect.Descriptor instead.
func (*StepStatus) Descriptor() ([]byte, []int) {
	return file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *StepStatus) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepStatus) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *StepStatus) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StepStatus) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *StepStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StepStatus) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

type RunTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	PlanId        string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Statuses      []*StepStatus          `protobuf:"bytes,4,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Blocked       bool                   `protobuf:"varint,5,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Document      string                 `protobuf:"bytes,7,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskResponse) Reset() {
	*x = RunTaskResponse{}
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskResponse) ProtoMessage() {}

func (x *RunTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskResponse.ProtoReflect.Descriptor instead.
func (*RunTaskResponse) Descriptor() ([]byte, []int) {
	return file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *RunTaskResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RunTaskResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RunTaskResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *RunTaskResponse) GetStatuses() []*StepStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *RunTaskResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *RunTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunTaskResponse) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

var File_ai_agent_orchestrator_ai_agent_orchestrator_proto protoreflect.FileDescriptor

const file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDesc = "" +
	"\n" +
	"1ai-agent-orchestrator/ai_agent_orchestrator.proto\x12\x0forchestrator.v1\x1a ai-agent-orchestrator/base.proto\"\xb6\x02\n" +
	"\bPlanStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tskill_ref\x18\x02 \x01(\tR\bskillRef\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x04 \x01(\tR\tfeatureId\x12\x13\n" +
	"\x05uc_id\x18\x05 \x01(\tR\x04ucId\x127\n" +
	"\x04meta\x18\x06 \x03(\v2#.orchestrator.v1.PlanStep.MetaEntryR\x04meta\x12\x1f\n" +
	"\vper_feature\x18\a \x01(\bR\n" +
	"perFeature\x12\x15\n" +
	"\x06per_uc\x18\b \x01(\bR\x05perUc\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\tPlanPhase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12/\n" +
	"\x05steps\x18\x03 \x03(\v2\x19.orchestrator.v1.PlanStepR\x05steps\"\x8b\x03\n" +
	"\rExecutionPlan\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.orchestrator.v1.MetadataR\bmetadata\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.orchestrator.v1.ResultR\x06result\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x04 \x01(\tR\n" +
	"documentId\x122\n" +
	"\x06phases\x18\x05 \x03(\v2\x1a.orchestrator.v1.PlanPhaseR\x06phases\x12\x1f\n" +
	"\vfeature_ids\x18\x06 \x03(\tR\n" +
	"featureIds\x12\x15\n" +
	"\x06uc_ids\x18\a \x03(\tR\x05ucIds\x12<\n" +
	"\x04meta\x18\b \x03(\v2(.orchestrator.v1.ExecutionPlan.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\x11CreatePlanRequest\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.orchestrator.v1.MetadataR\bmetadata\x128\n" +
	"\tsignature\x18\x02 \x01(\v2\x1a.orchestrator.v1.SignatureR\tsignature\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x12\n" +
	"\x04goal\x18\x04 \x01(\tR\x04goal\x12\x1f\n" +
	"\vfeature_ids\x18\x05 \x03(\tR\n" +
	"featureIds\x12\x15\n" +
	"\x06uc_ids\x18\x06 \x03(\tR\x05ucIds\"\xe6\x02\n" +
	"\x0eRunTaskRequest\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.orchestrator.v1.MetadataR\bmetadata\x128\n" +
	"\tsignature\x18\x02 \x01(\v2\x1a.orchestrator.v1.SignatureR\tsignature\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x12\n" +
	"\x04goal\x18\x04 \x01(\tR\x04goal\x12\x1f\n" +
	"\vfeature_ids\x18\x05 \x03(\tR\n" +
	"featureIds\x12\x15\n" +
	"\x06uc_ids\x18\x06 \x03(\tR\x05ucIds\x12=\n" +
	"\x04meta\x18\a \x03(\v2).orchestrator.v1.RunTaskRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x01\n" +
	"\n" +
	"StepStatus\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x18\n" +
	"\ablocked\x18\x04 \x01(\bR\ablocked\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1a\n" +
	"\bdocument\x18\x06 \x01(\tR\bdocument\"\x97\x02\n" +
	"\x0fRunTaskResponse\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.orchestrator.v1.MetadataR\bmetadata\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.orchestrator.v1.ResultR\x06result\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x127\n" +
	"\bstatuses\x18\x04 \x03(\v2\x1b.orchestrator.v1.StepStatusR\bstatuses\x12\x18\n" +
	"\ablocked\x18\x05 \x01(\bR\ablocked\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1a\n" +
	"\bdocument\x18\a \x01(\tR\bdocument2\x86\x02\n" +
	"\x13OrchestratorService\x12L\n" +
	"\aRunTask\x12\x1f.orchestrator.v1.RunTaskRequest\x1a .orchestrator.v1.RunTaskResponse\x12P\n" +
	"\n" +
	"CreatePlan\x12\".orchestrator.v1.CreatePlanRequest\x1a\x1e.orchestrator.v1.ExecutionPlan\x12O\n" +
	"\vExecutePlan\x12\x1e.orchestrator.v1.ExecutionPlan\x1a .orchestrator.v1.RunTaskResponseBk\n" +
	"$com.blcvn.kratos.protos.orchestratorZCgithub.com/blcvn/kratos-proto/go/ai-agent-orchestrator;orchestratorb\x06proto3"

var (
	file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescOnce sync.Once
	file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescData []byte
)

func file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescGZIP() []byte {
	file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescOnce.Do(func() {
		file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDesc), len(file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDesc)))
	})
	return file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDescData
}

var file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ai_agent_orchestrator_ai_agent_orchestrator_proto_goTypes = []any{
	(*PlanStep)(nil),          // 0: orchestrator.v1.PlanStep
	(*PlanPhase)(nil),         // 1: orchestrator.v1.PlanPhase
	(*ExecutionPlan)(nil),     // 2: orchestrator.v1.ExecutionPlan
	(*CreatePlanRequest)(nil), // 3: orchestrator.v1.CreatePlanRequest
	(*RunTaskRequest)(nil),    // 4: orchestrator.v1.RunTaskRequest
	(*StepStatus)(nil),        // 5: orchestrator.v1.StepStatus
	(*RunTaskResponse)(nil),   // 6: orchestrator.v1.RunTaskResponse
	nil,                       // 7: orchestrator.v1.PlanStep.MetaEntry
	nil,                       // 8: orchestrator.v1.ExecutionPlan.MetaEntry
	nil,                       // 9: orchestrator.v1.RunTaskRequest.MetaEntry
	(*Metadata)(nil),          // 10: orchestrator.v1.Metadata
	(*Result)(nil),            // 11: orchestrator.v1.Result
	(*Signature)(nil),         // 12: orchestrator.v1.Signature
}
var file_ai_agent_orchestrator_ai_agent_orchestrator_proto_depIdxs = []int32{
	7,  // 0: orchestrator.v1.PlanStep.meta:type_name -> orchestrator.v1.PlanStep.MetaEntry
	0,  // 1: orchestrator.v1.PlanPhase.steps:type_name -> orchestrator.v1.PlanStep
	10, // 2: orchestrator.v1.ExecutionPlan.metadata:type_name -> orchestrator.v1.Metadata
	11, // 3: orchestrator.v1.ExecutionPlan.result:type_name -> orchestrator.v1.Result
	1,  // 4: orchestrator.v1.ExecutionPlan.phases:type_name -> orchestrator.v1.PlanPhase
	8,  // 5: orchestrator.v1.ExecutionPlan.meta:type_name -> orchestrator.v1.ExecutionPlan.MetaEntry
	10, // 6: orchestrator.v1.CreatePlanRequest.metadata:type_name -> orchestrator.v1.Metadata
	12, // 7: orchestrator.v1.CreatePlanRequest.signature:type_name -> orchestrator.v1.Signature
	10, // 8: orchestrator.v1.RunTaskRequest.metadata:type_name -> orchestrator.v1.Metadata
	12, // 9: orchestrator.v1.RunTaskRequest.signature:type_name -> orchestrator.v1.Signature
	9,  // 10: orchestrator.v1.RunTaskRequest.meta:type_name -> orchestrator.v1.RunTaskRequest.MetaEntry
	10, // 11: orchestrator.v1.RunTaskResponse.metadata:type_name -> orchestrator.v1.Metadata
	11, // 12: orchestrator.v1.RunTaskResponse.result:type_name -> orchestrator.v1.Result
	5,  // 13: orchestrator.v1.RunTaskResponse.statuses:type_name -> orchestrator.v1.StepStatus
	4,  // 14: orchestrator.v1.OrchestratorService.RunTask:input_type -> orchestrator.v1.RunTaskRequest
	3,  // 15: orchestrator.v1.OrchestratorService.CreatePlan:input_type -> orchestrator.v1.CreatePlanRequest
	2,  // 16: orchestrator.v1.OrchestratorService.ExecutePlan:input_type -> orchestrator.v1.ExecutionPlan
	6,  // 17: orchestrator.v1.OrchestratorService.RunTask:output_type -> orchestrator.v1.RunTaskResponse
	2,  // 18: orchestrator.v1.OrchestratorService.CreatePlan:output_type -> orchestrator.v1.ExecutionPlan
	6,  // 19: orchestrator.v1.OrchestratorService.ExecutePlan:output_type -> orchestrator.v1.RunTaskResponse
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_ai_agent_orchestrator_ai_agent_orchestrator_proto_init() }
func file_ai_agent_orchestrator_ai_agent_orchestrator_proto_init() {
	if File_ai_agent_orchestrator_ai_agent_orchestrator_proto != nil {
		return
	}
	file_ai_agent_orchestrator_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDesc), len(file_ai_agent_orchestrator_ai_agent_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_agent_orchestrator_ai_agent_orchestrator_proto_goTypes,
		DependencyIndexes: file_ai_agent_orchestrator_ai_agent_orchestrator_proto_depIdxs,
		MessageInfos:      file_ai_agent_orchestrator_ai_agent_orchestrator_proto_msgTypes,
	}.Build()
	File_ai_agent_orchestrator_ai_agent_orchestrator_proto = out.File
	file_ai_agent_orchestrator_ai_agent_orchestrator_proto_goTypes = nil
	file_ai_agent_orchestrator_ai_agent_orchestrator_proto_depIdxs = nil
}
