// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: feature/feature.proto

package feature

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeatureService_CreateFeature_FullMethodName    = "/feature.v1.FeatureService/CreateFeature"
	FeatureService_UpdateFeature_FullMethodName    = "/feature.v1.FeatureService/UpdateFeature"
	FeatureService_GetFeature_FullMethodName       = "/feature.v1.FeatureService/GetFeature"
	FeatureService_ListFeatures_FullMethodName     = "/feature.v1.FeatureService/ListFeatures"
	FeatureService_DeleteFeature_FullMethodName    = "/feature.v1.FeatureService/DeleteFeature"
	FeatureService_CreateDoc_FullMethodName        = "/feature.v1.FeatureService/CreateDoc"
	FeatureService_ListDocs_FullMethodName         = "/feature.v1.FeatureService/ListDocs"
	FeatureService_GetDocContent_FullMethodName    = "/feature.v1.FeatureService/GetDocContent"
	FeatureService_UpdateDocContent_FullMethodName = "/feature.v1.FeatureService/UpdateDocContent"
	FeatureService_GetChatHistory_FullMethodName   = "/feature.v1.FeatureService/GetChatHistory"
	FeatureService_SendMessage_FullMethodName      = "/feature.v1.FeatureService/SendMessage"
)

// FeatureServiceClient is the client API for FeatureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =======================
// Feature Service Definition
// =======================
type FeatureServiceClient interface {
	// Create Feature
	CreateFeature(ctx context.Context, in *CreateFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error)
	// Update Feature
	UpdateFeature(ctx context.Context, in *UpdateFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error)
	// Get Feature
	GetFeature(ctx context.Context, in *GetFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error)
	// List Features (Children of a parent or project root)
	ListFeatures(ctx context.Context, in *ListFeaturesRequest, opts ...grpc.CallOption) (*ListFeaturesReply, error)
	// Delete Feature
	DeleteFeature(ctx context.Context, in *DeleteFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error)
	// Document Management
	CreateDoc(ctx context.Context, in *CreateDocRequest, opts ...grpc.CallOption) (*FeatureDoc, error)
	ListDocs(ctx context.Context, in *ListDocsRequest, opts ...grpc.CallOption) (*ListDocsReply, error)
	GetDocContent(ctx context.Context, in *GetDocContentRequest, opts ...grpc.CallOption) (*DocContentReply, error)
	UpdateDocContent(ctx context.Context, in *UpdateDocContentRequest, opts ...grpc.CallOption) (*DocContentReply, error)
	// Chat Management
	GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*ChatHistoryReply, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*ChatMessage, error)
}

type featureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeatureServiceClient(cc grpc.ClientConnInterface) FeatureServiceClient {
	return &featureServiceClient{cc}
}

func (c *featureServiceClient) CreateFeature(ctx context.Context, in *CreateFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureReply)
	err := c.cc.Invoke(ctx, FeatureService_CreateFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) UpdateFeature(ctx context.Context, in *UpdateFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureReply)
	err := c.cc.Invoke(ctx, FeatureService_UpdateFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) GetFeature(ctx context.Context, in *GetFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureReply)
	err := c.cc.Invoke(ctx, FeatureService_GetFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) ListFeatures(ctx context.Context, in *ListFeaturesRequest, opts ...grpc.CallOption) (*ListFeaturesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeaturesReply)
	err := c.cc.Invoke(ctx, FeatureService_ListFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) DeleteFeature(ctx context.Context, in *DeleteFeatureRequest, opts ...grpc.CallOption) (*FeatureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureReply)
	err := c.cc.Invoke(ctx, FeatureService_DeleteFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) CreateDoc(ctx context.Context, in *CreateDocRequest, opts ...grpc.CallOption) (*FeatureDoc, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureDoc)
	err := c.cc.Invoke(ctx, FeatureService_CreateDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) ListDocs(ctx context.Context, in *ListDocsRequest, opts ...grpc.CallOption) (*ListDocsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocsReply)
	err := c.cc.Invoke(ctx, FeatureService_ListDocs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) GetDocContent(ctx context.Context, in *GetDocContentRequest, opts ...grpc.CallOption) (*DocContentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocContentReply)
	err := c.cc.Invoke(ctx, FeatureService_GetDocContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) UpdateDocContent(ctx context.Context, in *UpdateDocContentRequest, opts ...grpc.CallOption) (*DocContentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocContentReply)
	err := c.cc.Invoke(ctx, FeatureService_UpdateDocContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*ChatHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatHistoryReply)
	err := c.cc.Invoke(ctx, FeatureService_GetChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*ChatMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMessage)
	err := c.cc.Invoke(ctx, FeatureService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeatureServiceServer is the server API for FeatureService service.
// All implementations must embed UnimplementedFeatureServiceServer
// for forward compatibility.
//
// =======================
// Feature Service Definition
// =======================
type FeatureServiceServer interface {
	// Create Feature
	CreateFeature(context.Context, *CreateFeatureRequest) (*FeatureReply, error)
	// Update Feature
	UpdateFeature(context.Context, *UpdateFeatureRequest) (*FeatureReply, error)
	// Get Feature
	GetFeature(context.Context, *GetFeatureRequest) (*FeatureReply, error)
	// List Features (Children of a parent or project root)
	ListFeatures(context.Context, *ListFeaturesRequest) (*ListFeaturesReply, error)
	// Delete Feature
	DeleteFeature(context.Context, *DeleteFeatureRequest) (*FeatureReply, error)
	// Document Management
	CreateDoc(context.Context, *CreateDocRequest) (*FeatureDoc, error)
	ListDocs(context.Context, *ListDocsRequest) (*ListDocsReply, error)
	GetDocContent(context.Context, *GetDocContentRequest) (*DocContentReply, error)
	UpdateDocContent(context.Context, *UpdateDocContentRequest) (*DocContentReply, error)
	// Chat Management
	GetChatHistory(context.Context, *GetChatHistoryRequest) (*ChatHistoryReply, error)
	SendMessage(context.Context, *SendMessageRequest) (*ChatMessage, error)
	mustEmbedUnimplementedFeatureServiceServer()
}

// UnimplementedFeatureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeatureServiceServer struct{}

func (UnimplementedFeatureServiceServer) CreateFeature(context.Context, *CreateFeatureRequest) (*FeatureReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFeature not implemented")
}
func (UnimplementedFeatureServiceServer) UpdateFeature(context.Context, *UpdateFeatureRequest) (*FeatureReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFeature not implemented")
}
func (UnimplementedFeatureServiceServer) GetFeature(context.Context, *GetFeatureRequest) (*FeatureReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeature not implemented")
}
func (UnimplementedFeatureServiceServer) ListFeatures(context.Context, *ListFeaturesRequest) (*ListFeaturesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeatures not implemented")
}
func (UnimplementedFeatureServiceServer) DeleteFeature(context.Context, *DeleteFeatureRequest) (*FeatureReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFeature not implemented")
}
func (UnimplementedFeatureServiceServer) CreateDoc(context.Context, *CreateDocRequest) (*FeatureDoc, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDoc not implemented")
}
func (UnimplementedFeatureServiceServer) ListDocs(context.Context, *ListDocsRequest) (*ListDocsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocs not implemented")
}
func (UnimplementedFeatureServiceServer) GetDocContent(context.Context, *GetDocContentRequest) (*DocContentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocContent not implemented")
}
func (UnimplementedFeatureServiceServer) UpdateDocContent(context.Context, *UpdateDocContentRequest) (*DocContentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDocContent not implemented")
}
func (UnimplementedFeatureServiceServer) GetChatHistory(context.Context, *GetChatHistoryRequest) (*ChatHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatHistory not implemented")
}
func (UnimplementedFeatureServiceServer) SendMessage(context.Context, *SendMessageRequest) (*ChatMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedFeatureServiceServer) mustEmbedUnimplementedFeatureServiceServer() {}
func (UnimplementedFeatureServiceServer) testEmbeddedByValue()                        {}

// UnsafeFeatureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeatureServiceServer will
// result in compilation errors.
type UnsafeFeatureServiceServer interface {
	mustEmbedUnimplementedFeatureServiceServer()
}

func RegisterFeatureServiceServer(s grpc.ServiceRegistrar, srv FeatureServiceServer) {
	// If the following call panics, it indicates UnimplementedFeatureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeatureService_ServiceDesc, srv)
}

func _FeatureService_CreateFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).CreateFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_CreateFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).CreateFeature(ctx, req.(*CreateFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_UpdateFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).UpdateFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_UpdateFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).UpdateFeature(ctx, req.(*UpdateFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_GetFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).GetFeature(ctx, req.(*GetFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_ListFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).ListFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_ListFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).ListFeatures(ctx, req.(*ListFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_DeleteFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).DeleteFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_DeleteFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).DeleteFeature(ctx, req.(*DeleteFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_CreateDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).CreateDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_CreateDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).CreateDoc(ctx, req.(*CreateDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_ListDocs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).ListDocs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_ListDocs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).ListDocs(ctx, req.(*ListDocsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_GetDocContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).GetDocContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_GetDocContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).GetDocContent(ctx, req.(*GetDocContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_UpdateDocContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).UpdateDocContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_UpdateDocContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).UpdateDocContent(ctx, req.(*UpdateDocContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_GetChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).GetChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_GetChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).GetChatHistory(ctx, req.(*GetChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeatureService_ServiceDesc is the grpc.ServiceDesc for FeatureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeatureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feature.v1.FeatureService",
	HandlerType: (*FeatureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFeature",
			Handler:    _FeatureService_CreateFeature_Handler,
		},
		{
			MethodName: "UpdateFeature",
			Handler:    _FeatureService_UpdateFeature_Handler,
		},
		{
			MethodName: "GetFeature",
			Handler:    _FeatureService_GetFeature_Handler,
		},
		{
			MethodName: "ListFeatures",
			Handler:    _FeatureService_ListFeatures_Handler,
		},
		{
			MethodName: "DeleteFeature",
			Handler:    _FeatureService_DeleteFeature_Handler,
		},
		{
			MethodName: "CreateDoc",
			Handler:    _FeatureService_CreateDoc_Handler,
		},
		{
			MethodName: "ListDocs",
			Handler:    _FeatureService_ListDocs_Handler,
		},
		{
			MethodName: "GetDocContent",
			Handler:    _FeatureService_GetDocContent_Handler,
		},
		{
			MethodName: "UpdateDocContent",
			Handler:    _FeatureService_UpdateDocContent_Handler,
		},
		{
			MethodName: "GetChatHistory",
			Handler:    _FeatureService_GetChatHistory_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _FeatureService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feature/feature.proto",
}
